### ISSUE TITLE
How to remove console.log during minify

### ISSUE THREAD

**Issue by cooolbasha** [terinjokes/gulp-uglify#10]
Is there a way to specify that console.log should be removed.

**Comment by ptim** [comment]
Thanks.. here's wayback's capture of that dead link: http://web.archive.org/web/20141115053409/http://jstarrdewar.com/blog/2013/02/28/use-uglify-to-automatically-strip-debug-messages-from-your-javascript/

in short: 

```
    if (typeof DEBUG === 'undefined') DEBUG = true; // will be removed

    function doSomethingCool() {
        DEBUG && console.log("something cool just happened"); // will be removed
    }
```

then:


    uglifyjs --compress --define DEBUG=false main.js -o main.min2.js

**Comment by AlexanderKozhevin** [comment]
I think it's a way better to implement it as an option in plugin itself. Like in webpack **drop_console**.

**Comment by terinjokes** [comment]
Yes, there's now an option for this! Please use the option `{ compress: { drop_console: true } }`.

Dead Code Elimation is still good for lots of other things, but this is not one of them.
