### ISSUE TITLE
Support for es6 modules?

### ISSUE THREAD

**Issue by f0rmat1k** [terinjokes/gulp-uglify#102]
I have string `export default SomeModule;` and getting the error `Unexpected token: keyword (default)`

**Comment by dangreenisrael** [comment]
I also have an issue with this.  Are you using ember-cli?

**Comment by f0rmat1k** [comment]
@dangreenisrael no, i'm just using gulp-cli. It's the problem of [uglify-js](https://github.com/mishoo/UglifyJS2/issues/448)
