### ISSUE TITLE
Doesn't Parse Selectivizr correclty

### ISSUE THREAD

**Issue by revxx14** [terinjokes/gulp-uglify#103]
I often use the script [Selectivizr](http://selectivizr.com/) in my projects, but it isn't getting uglified properly. Looks like it's not compressing after this section of code:

    // If browser isn't IE, then stop execution! This handles the script 
    // being loaded by non IE browsers because the developer didn't use 
    // conditional comments.
    if (/*@cc_on!@*/true) return;

The entire script outputs as:

    !function(n){return}(this);

Which obviously isn't correct.

For now, I've switched to:

    if (navigator.appName == "Microsoft Internet Explorer") {
        return;
    }

Which theoretically should fix the problem for the time being, but I think this is something that should be fixed for a future release.

**Comment by Poetro** [comment]
If you say in the middle of the code, to return, without any condition, then it obviously cuts everything after it. And in any other case, this is not an issue of gulp-uglify.

**Comment by terinjokes** [comment]
@revxx14 This is expected, as from the perspective of UglifyJS, everything else is dead code. You can turn off the dead code remover by passing the "dead_code" compressor option.

```json
{
  "compress": {
    "dead_code": false
  }
}
```
