### ISSUE TITLE
semicolon replaced by a comma

### ISSUE THREAD

**Issue by emaza** [terinjokes/gulp-uglify#108]
//This task (with or width out mangle) 
gulp.task('ctrl', function() {
    return gulp.src('../js/controllers/*.js')
        .pipe(uglify({mangle:false}))
        .pipe(gulp.dest('../js/controllers'))
});

//for this original code
/* General controller for all exercises */
var app = angular.module('app', []);

app.directive("dirDelete", function () {
    return {
        scope: '',
        controller: function ($scope) {
            scope = $scope;
        },
        link: function (scope, element, attr) {
            setTimeout(function () {
                if (!element.parent().is(":visible")) {
                    element.parent().remove();

                } else {
                    scope.interactive.push(element)
                }
            }, 100)

        }
    }
});

// d = directive
//
//
// TODO
//
//<octs-d-mini-audio></octs-d-mini-audio>
app.directive("octsDMiniAudio", function() {
	return {
		restrict: 'E',
        transclude: true,
		replace: false,
		templateUrl: url_common_files + 'includes/elements/mini-audio.html'
	};
});

//
//<octs-d-block-images></octs-block-images>
app.directive("octsDBlockImages", function() {
	return {
		restrict: 'E',
		replace: true,
		templateUrl: url_common_files + 'includes/elements/block-images.html'
	};
});
(...)
//Generate this code (rebeautify)
var app = angular.module("app", []);
app.directive("dirDelete", function () {
    return {
        scope: "",
        controller: function ($scope) {
            scope = $scope
        },
        link: function (scope, element, attr) {
            setTimeout(function () {
                element.parent().is(":visible") ? scope.interactive.push(element) : element.parent().remove()
            }, 100)
        }
    }
}), app.directive("octsDMiniAudio", function () {
    return {
        restrict: "E",
        transclude: !0,
        replace: !1,
        templateUrl: url_common_files + "includes/elements/mini-audio.html"
    }
}), app.directive("octsDBlockImages", function () {
    return {
        restrict: "E",
        replace: !0,
        templateUrl: url_common_files + "includes/elements/block-images.html"
    }
}),
(...)

//Look comma before app.directive
//Thanks

**Comment by shinnn** [comment]
@emaza 

1. You should rewrite [this comment](https://github.com/terinjokes/gulp-uglify/issues/108#issue-86149795) with correct [markdown syntax highlighting](https://help.github.com/articles/github-flavored-markdown/#syntax-highlighting) for more readability.
2. This seems [UglifyJS](https://github.com/mishoo/UglifyJS2) issue.

**Comment by terinjokes** [comment]
This is an issue with UglifyJS, please file an issue on their issue tracker. Thanks.

**Comment by emaza** [comment]
ok so sorry and thanks
