### ISSUE TITLE
Switch to suppress parse errors

### ISSUE THREAD

**Issue by mikkotikkanen** [terinjokes/gulp-uglify#110]
When using components fe. from Bower (which might come with source files split to different files, or any broken files for building etc) the possible parse errors in any random file kills the whole minifying process and you have to separately remove them from source files.

For cases like this it would be handy if `gulp-uglify` would have `supressErrors` option, which, instead of triggering error on parse issues (which ends the whole process), would just console.log out a warning, skip that file and keep chugging along. Much like r.js does it. (Except that it doesn't even show any warnings)

Uglify itself doesn't have switch for this since the recommended way to do this in uglify would be to wrap the call in try-catch block. https://github.com/mishoo/UglifyJS2/issues/620

**Comment by Poetro** [comment]
Have you tried `gulp-plumber`? Does that not solve the issue?

**Comment by mikkotikkanen** [comment]
Yeah, I'm using it but unfortunately it doesn't fix said issue, it only fixes the error handling on gulp streams, it however doesn't prevent uglify breaking on parse error. :/

This is how r.js does it

```js
try {
    // run optimizer
} catch (e) {
    if (config.throwWhen && config.throwWhen.optimize) {
        throw e;
    }
}
```

**Comment by terinjokes** [comment]
As an alternative, have you considered using a series of gulp-concats to create whole files from the pieces of bower components?

**Comment by mikkotikkanen** [comment]
That doesn't solve the situation either since the bower components (as does node modules as well) usually come with development, test & build files as well, so I would be building extra weight to each component. :/ Specially since files are loaded with RequireJS, so only files that are needed are loaded.

**Comment by mikkotikkanen** [comment]
Did alternative to this as a custom error handler function that you can pass to gulp-uglify. This way it's the most flexible solution possible.
(started to think that it would still be nice to have errors on some critical files, whereas its completely ok if some random library file, that is not even used, doesn't minify. So one can write their own logic of when to trigger errors and when not.)

**Comment by terinjokes** [comment]
Why can't you resolve this by using rjs to generate bundles and minify those?

**Comment by sindresorhus** [comment]
:-1: Way outside the scope of this plugin. You should also seriously consider if pulling in a bunch of random files and using the ones that don't throw a parse error is the best approach.

**Comment by terinjokes** [comment]
I don't think having a custom error handler is a good fit for this plugin. `gulp-uglify` assumes it's a part of a production release process and is feed complete and valid JavaScript files. It reports an error when something is wrong that should abort a release process.

At some point, you must be taking the JavaScript partials you're currently trying to pass to `gulp-uglify` and turning them into something that a browser will execute without error, and `gulp-uglify` is happen to be used at the end of this process;
