### ISSUE TITLE
Uglifying top-level functions

### ISSUE THREAD

**Issue by surajreddy** [terinjokes/gulp-uglify#113]
Does this support uglifying top-level functions as well? (Ex: Global Class names)

We've tried uglify({mangle: {toplevel: true}}) but this didn't do the trick.

**Comment by terinjokes** [comment]
@surajreddy I don't understand, do you mind providing an example of what you mean?

**Comment by tehXor** [comment]
He means that top level function names don't get mangled (probably because this is not the default in UglifyJS2) and that specifying the corresponding option which would work with pure UglifyJS2 doesn't work...

That being said for those who are looking for a pure wrapper of UglifyJS2 for Gulp which doesn't try to abstract options away (for whatever reason) gulp-uglifyjs-wrapper simplay works (obviously also with the toplevel mangle option): https://www.npmjs.com/package/gulp-uglifyjs-wrapper/

**Comment by terinjokes** [comment]
@surajreddy I'm using gulp-uglify version 1.4.2 with the following as "input.js":

```javascript
function mangleme() {
  return 'manled';
}
```

And i've setup the following gulp pipeline.

```javascript
gulp.task('compress', function() {
  return gulp.src('./input.js')
    .pipe(uglify({
       mangled: { toplevel: true }
     }))
    .pipe(gulp.dest('dist'));
});
```

And I get the following output:

```javascript
function n(){return"mangled"}
```

If you do not, please upload a reproducible test case so I may determine why.

**Comment by surajreddy** [comment]
Hi @terinjokes, thanks for following up on this! 

I am still having issues. This is the code I am using:

JS:
```javascript
function mangleme() {
  return 'manled';
}

mangleme();

var B;

B.manglethistoo = function test() {
    return 'this should also be mangled';
};

B.manglethistoo();
```

Gulp Code:
```javascript
var gulp = require('gulp'),
    uglify = require('gulp-uglify');

gulp.task('compress', function() {
  return gulp.src('./input.js')
    .pipe(uglify({
       mangled: { toplevel: true }
     }))
    .pipe(gulp.dest('output'));
});
```

Output:
```javascript
function mangleme(){return"manled"}mangleme();var B;B.manglethistoo=function(){return"this should also be mangled"},B.manglethistoo();
```

Output I am expecting/trying to get:
```javascript
function n(){return"manled"}n();var B;B.z=function(){return"this should also be mangled"},B.z();
```

**Comment by terinjokes** [comment]
@surajreddy This may be an issue with UglifyJS, but I'm double checking.

**Comment by terinjokes** [comment]
@surajreddy I misread your response earlier.

> how do I also mangle B.manglethistoo as well? Or is this not supported?

Mangling property names is currently not supported (see also #115, where I explain that I can't even pass an option to UglifyJS's API to enable it)

**Comment by surajreddy** [comment]
Got it, thanks!
