### ISSUE TITLE
for...of loop error

### ISSUE THREAD

**Issue by SebastianZimmer** [terinjokes/gulp-uglify#114]
When trying to uglify a for...of loop (https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Statements/for...of), the process fails with this error message:
Unexpected token name «of», expected punc «;»

**Comment by farin** [comment]
it would be nice upgrade dependency to latest uglify-js with better ES6 support

**Comment by terinjokes** [comment]
UglifyJS does not currently support ES6, please use a transformation system such as [Babel](https://babeljs.io) before passing the code to UglifyJS.
