### ISSUE TITLE
Mangle properties support (--mangle-props)

### ISSUE THREAD

**Issue by carlmartus** [terinjokes/gulp-uglify#115]
In the uglify cli program you can pass the parameter "--mangle-props" to tell uglify to mangle object field varable names. Having this as a in the gulpfile would be nice.

**Comment by macinjosh32** [comment]
+1

**Comment by mouda3** [comment]
+ 1

**Comment by CrimsonChris** [comment]
Any workaround to do this now?

**Comment by jbjorge** [comment]
+1

**Comment by askmatey** [comment]
:+1:

**Comment by terinjokes** [comment]
Please file an upstream issue with UglifyJS, there does not seem to be a way to enable this from the documented API.

**Comment by mbrevda** [comment]
Is [this](https://github.com/gruntjs/grunt-contrib-uglify/blob/master/tasks/lib/uglify.js#L120-L134) how you can mangle properties programmatically?

**Comment by terinjokes** [comment]
Yes, but this requires reimplementing all of UglifyJS's CLI tool, when they
should be adding the features to their library interface.

**Comment by ramon18** [comment]
+1

**Comment by kdelmonte** [comment]
FYI. PR https://github.com/mishoo/UglifyJS2/pull/910 has been merged.

**Comment by terinjokes** [comment]
@kdelmonte Thanks for the heads up, Greenkeeper should send me a PR when it hits npm.

**Comment by Ajaxy** [comment]
Was it finally released? What version?

**Comment by Ajaxy** [comment]
Guys?

**Comment by toddhgardner** [comment]
FYI this appears to work already with a `mangleProperties` option.

**Comment by Ajaxy** [comment]
thanks!

**Comment by zhaiduo** [comment]
When will gulp-uglify work with mangleProperties?

**Comment by jbartek25** [comment]
Actually gulp-uglify already works with mangleProperties. The format is:
```
mangle: {
  // mangle options
  properties: {
    // mangle property options
  }
}
```
Example:
```
mangle: {
  properties: {
     regex: /^[A-Z0-9_]+$/
  }
}
```
