### ISSUE TITLE
can enable  param "mangle-regex"? uglifyjs2 is added it.

### ISSUE THREAD

**Issue by benleilei** [terinjokes/gulp-uglify#117]
can enable  param "mangle-regex"? uglifyjs2 is added it.

**Comment by kuus** [comment]
+ 1

**Comment by kuus** [comment]
+ 1

**Comment by kuus** [comment]
:thumbsup:

**Comment by terinjokes** [comment]
gulp-uglify doesn't is primarily an adapter around UglifyJS's library. Unfortunately, they implemented this feature as part of the CLI tool, not the library. Can you file a bug with them?

**Comment by hisplan** [comment]
+1

**Comment by terinjokes** [comment]
As noted in July, please fill a bug with UglifyJS to add this to their programmatic interface.
