### ISSUE TITLE
Firefox error

### ISSUE THREAD

**Issue by Ubitso** [terinjokes/gulp-uglify#119]
I get an error in my uglifyed code:

    TypeError: 0 is read-only

Error occurs only in Firefox 39.0.
In Firefox 37.0 all working well.
gulp-uglify v1.2.0

My task:

    uglify({
        compress: {
            unsafe: false,
            warnings: false,
            conditionals: false,
            comparisons: false,
            evaluate: false,
            if_return: false
       }
    })

Which options I should use to get no error?

**Comment by terinjokes** [comment]
gulp-uglify is a wrapper around [UglifyJS](https://github.com/mishoo/UglifyJS2). Please report your issue on their issue tracker with a reproducible case so their developers can take a look.
