### ISSUE TITLE
gulp-uglify messes with unicode string

### ISSUE THREAD

**Issue by Giszmo** [terinjokes/gulp-uglify#120]
angular.js currency filter uses ¤ to replace it later with 'USD' for example. Relevant lines are:
`{ … posPre: '\u00A4', … negPre: '(\u00A4', … }` and then later `replace(/\u00A4/g, currencySymbol)`.

`"gulp-uglify": "^1.2.0"` does not uglify the regexp but it converts the object into `{ … posPre: 'Â¤', … negPre: '(Â¤', … }`

The result is that using the currency filter yields ÂUSD instead of USD.

Is there a flag to not mess with any strings?

**Comment by Giszmo** [comment]
I am very very confused right now. Anyway, patching angular.js and putting `BLAFOO` instead of `\u00A4` fixes my bug but this is not a solution and I'm trying to understand what's going on:

My gulp task browserifies some files and ulgifies them using gulp-uglify. Then cordova puts that to a different folder from where nginx serves it. Checking with grep on the console, I see `posPre:"¤"` in the file that actually should get served, not `posPre:"Â¤"` as claimed above. Same is true when looking at it with gedit. Atom.io fails to handle that 3MB file. In the browser though, I see the claimed `Â¤`, even after clearing the cache and making sure other changes show up there. This leads me to conclude that either there is some invisible something in the file (which I will try to locate in a binary editor) or this unwanted behavior of uglify triggers a bug in chrome and iceweasel. Bottom line is I would rather want gulp-uglify to leave the strings alone. `\u00A4` is a nice string as far as I'm concerned.

**Comment by Giszmo** [comment]
Ok, `uglify({output: {ascii_only:true}})` allows me to correctly uglify `angular.js` but I guess it still is a bug in gulp-uglify.

**Comment by terinjokes** [comment]
This sounds like a bug in UglifyJS (gulp-uglify doesn't do much) but I'll
take a look this weekend.

**Comment by prassh123** [comment]
+1. Thanks for the workaround @Giszmo

**Comment by terinjokes** [comment]
It looks like Cordova is serving the file to your app without encoding information in Content-Type or Content-Encoding. UglifyJS2 defaults to outputting UTF-8 (and converts `\u` notation to the respective UTF-8 bytes).

This is not a bug in `gulp-uglify`, and passing the `UglifyJS` option to output only ASCII characters resolves it.

I'll happy accept a PR that implements an example recipe.
