### ISSUE TITLE
add options (max-line-len)

### ISSUE THREAD

**Issue by kelerliao** [terinjokes/gulp-uglify#121]
https://github.com/mishoo/UglifyJS2
max-line-len (default 32000) -- maximum line length (for uglified code)

https://www.npmjs.com/package/grunt-contrib-uglify#maxlinelen
maxLineLen
Type: Number
Default: 32000
Limit the line length in symbols. Pass maxLineLen = 0 to disable this safety feature.

example:
uglify({'max-line-len': 100})

**Comment by arantir** [comment]
Options are passed through. Names are slightly different, they're underscored.
```javascript
uglify({
      output: {
        max_line_len: 80
      }
})
```

Here's the link from UglifyJS README:  http://lisperator.net/uglifyjs/codegen

**Comment by terinjokes** [comment]
Thanks @arantir!
