### ISSUE TITLE
Can't preserve sourceMap comment line.

### ISSUE THREAD

**Issue by cheshirsky** [terinjokes/gulp-uglify#123]
I'm using gulp + webpack + uglify in my project and I have source map files created by `webpack.SourceMapDevToolPlugin` plugin. Due to the fact that my modules structure is quite complicated uglifyJS source map or any other source map tools are not suitable for me.

All I need is just to preserve my `//# sourceMappingURL=[url]` comment at the end of file. Unfortunately I cant change file structure to avoid adding of extra semicolons.

I've tried to use either `preserveComment: function(node, comment) {...}` and `output.comments` options for that but it not works. After uglifyJS processing mapping comment is erased.

Here are a few rows of the uglifyJS input file example:

```javascript
// modules code goes here
/* 6 */
/***/ function(module, exports, __webpack_require__) {

        var __WEBPACK_AMD_DEFINE_RESULT__;/**
         * Models
         * @module models
         */
        !(__WEBPACK_AMD_DEFINE_RESULT__ = function (require, exports) {

            'use strict';

            /**
             * @constructor
             * @ngInject
             */
            var MyClass = function MyClass(proto) {
                this.data = [];
                this.p = MyClass;
            };
            MyClass.$inject = ["proto"];
            /**
             * Export Models
             */
            exports.MyClass = MyClass;

        }.call(exports, __webpack_require__, exports, module), __WEBPACK_AMD_DEFINE_RESULT__ !== undefined && (module.exports = __WEBPACK_AMD_DEFINE_RESULT__));


/***/ }
/******/ ])
});
;
//# sourceMappingURL=main.js.map
```

As a result then I use `preserveComment: function(node, comment) {...}` function sourceMappingURL comment is not in the list (even if `compressor` is disabled).

It would be great if you can give me some advices how to manage that problem. Or may be you can change the comments processing.

**Comment by terinjokes** [comment]
UglifyJS stores comments on the next AST node. As there's not a next AST node to store your source map comment on, UglifyJS simply deletes it.

There's nothing I can do about that.

**Comment by cheshirsky** [comment]
Thanks!
