### ISSUE TITLE
How to include folder name in sources.

### ISSUE THREAD

**Issue by thuey** [terinjokes/gulp-uglify#125]
I have a similar folder structure to the following:

<pre>
+ app
    + module1
            services.js
    + module2
            services.js
</pre>

I am using uglify and concat to generate module1.min.js, module1.min.js.map, module2.min.js, and module2.min.js.map files. For both module1 and module2, services.js is listed as a source. In Chrome, when it uses the map to unminify the files, only one services.js is produced. I can't see the other services.js. By hacking the uglify code, I've been able to prepend the folder where the file came from, so the sources show module1/services.js and module2/services.js. Chrome then unminifies both of these, and I can see them both correctly. Is there some configuration I'm missing that will include the folder name in the list of sources? Or is there a better way to do what I'm trying to do?

**Comment by terinjokes** [comment]
@thuey I set the source maps path to the vinyl object's `relative` property (see https://github.com/terinjokes/gulp-uglify/blob/eaeae133981f6ab7c0ed2d89fcdcd079b22b1504/minifier.js#L78). This path is set depending on how you call `gulp.src` and with what options.

**Comment by thuey** [comment]
Thank you!! Setting the "base" option of gulp.src did the trick
