### ISSUE TITLE
Option to keep new-line symbols.

### ISSUE THREAD

**Issue by limonte** [terinjokes/gulp-uglify#126]
Can you please add option to keep new-line symbols, e.g. `keepNewlineSymbols`, default `false`.

I personally prefer to keep new-line symbols in minified JS code as GZIP takes care of them.

Keeping new line symbols allows to catch errors and debug code on production without creating .js.map files.

**Comment by terinjokes** [comment]
@limonte UglifyJS has an output option `beautify` that does what you want, with knobs `indent_start`, `indent_level`, and `width`. See the [UglifyJS output documentation](http://lisperator.net/uglifyjs/codegen) for more details.

As noted in the README, you can use these as follows:

```javascript
var uglify = require('gulp-uglify');

gulp.task('compress', function() {
  return gulp.src('lib/*.js')
    .pipe(uglify({
      output: { beautify: true }
    }))
    .pipe(gulp.dest('dist'));
});
```

I'll happily accept a pull request with a recipe example. :smile:
