### ISSUE TITLE
CHANGELOG.md doesn't specifically call out breaking changes in 1.0.0

### ISSUE THREAD

**Issue by greim** [terinjokes/gulp-uglify#132]
This would be very convenient for those of us who'd like to upgrade to 1.x :)

**Comment by greim** [comment]
(Assuming there were any.)

**Comment by terinjokes** [comment]
There shouldn't have been any.

**Comment by greim** [comment]
Thanks. Was just being cautious because of the semver convention for major version bumps.

**Comment by terinjokes** [comment]
You should have been more concerned about the version numbers before 1.0.0 then. They mean nothing, and everything about the API could have changed.
