### ISSUE TITLE
1.4.2 causes errors on minification with module.exports

### ISSUE THREAD

**Issue by MikaAK** [terinjokes/gulp-uglify#141]
Not sure why but using gulp-uglify along with `es5-shim` causes a `module is undefined` error when the code gets to a `module.exports`. Downgrading to `1.4.1` solves this issue. Spent quite a few hours to figure this out a fix would be awesome!

**Comment by stringbeans** [comment]
+1 we're experiencing this as well. downgrading to 1.4.1 fixed it

**Comment by terinjokes** [comment]
Can you put together a gist that fails? I can't reproduce this.
