### ISSUE TITLE
gulp-uglify expects an object, non-object provided

### ISSUE THREAD

**Issue by alayek** [terinjokes/gulp-uglify#144]
Hi, I installed `gulp-uglify` today using `npm i --save-dev gulp-uglify`.

I followed this tutorial http://tylermcginnis.com/reactjs-tutorial-pt-2-building-react-applications-with-gulp-and-browserify/ to use `gulp-uglify` like this:

```
gulp.task('build', function(){
  gulp.src(path.JS)
    .pipe(react())
    .pipe(concat(path.MINIFIED_OUT))
    .pipe(uglify(path.MINIFIED_OUT))
    .pipe(gulp.dest(path.DEST_BUILD));
});
```
When I run `gulp build` in my terminal, I get this error message :
`gulp-uglify expects an object, non-object provided`

It was not necessarily an error message, the command exited with status 0.

When I loaded my `index.html` in browser, in console, I saw this error: `Uncaught TypeError: e.type is not a function`

I realize something has gone wrong in the uglification process. My `package.json` shows `"gulp-uglify": "^1.4.2"`.

Please help. How should I be calling the `uglify` function in gulp task? I checked the documentation in npmjs website, and all I could find was the `uglify()` function was being called without any argumment. But that won't be applicable here, since I want them to go to a different directory.

**Comment by terinjokes** [comment]
Hello @alayek!

Thanks for using `gulp-uglify`. Allow me to attempt to answer your questions one by one.

> When I run `gulp build` in my terminal, I get this error message :+1: 
`gulp-uglify expects an object, non-object provided`

Apologies, the tutorial you followed is slightly incorrect. `gulp-uglify` expects an options object (or nothing) as it's argument, but you're passing in either a string or an array.

Change `.pipe(uglify(path.MINIFIED_OUT))` to `.pipe(uglify())` to get rid of this warning.

> When I loaded my index.html in browser, in console, I saw this error: `Uncaught TypeError: e.type is not a function`

This is telling you that you're calling `type()` on something, and `type` is not a function. I recommend commenting out the `.pipe(uglify())` line in your gulpfile to see where the error message comes from.

**Comment by alayek** [comment]
Hello @terinjokes, here are a few other things I have tried since filing this issue:

I used 
```
.pipe(uglify({ 
            file:path.MINIFIED_OUT 
        }))
```

This took away the error message with latest gulp in the terminal. But the React components are still not being rendered. in browser console, I am getting the same error message.

In uninstalled latest `gulp-uglify` and reinstalled `gulp-uglify@1.1.0` and used it as provided in the tutorial.

Still the same thing - uglification succeeds, but the JS code fails in browser.

I removed the uglification step altogether, and it produced the following output:

```
React.render(React.createElement(Parent, null), document.getElementById('app'));
var Child = React.createClass({displayName: "Child",
    propTypes: function() {
        name: React.PropTypes.String.isRequired
    },

    render: function(){
        return (
            React.createElement("div", null, 
                "and this is the ", React.createElement("b", null, this.props.name), "."
            )
        );
    }
});
var Parent = React.createClass({displayName: "Parent",
    render: function(){
        return (
            React.createElement("div", null, 
                React.createElement("div", null, " This is the parent. "), 
                React.createElement(Child, {name: "child"})
            )
        );
    }
});
```

This one renders the React components just fine. So, my original JS code is fine, and the concatenation works too. But the uglification step messes up something, and the react.min.js cannot render my components.

**Comment by terinjokes** [comment]
```
.pipe(uglify({ 
            file:path.MINIFIED_OUT 
        }))
```

The file option does nothing, you may remove it at your leisure.
---

As for your issue, I recommend using Chrome's debugger and investigating the state of the application when you encounter the error.

**Comment by AndreaIannitti** [comment]
I went through the same tutorial and I ran into the same issue.
By looking at the concatenated code, the React.render(...) call does not know the Parent class because it's defined later.
I moved the first line to the bottom and it worked.
So basically, in the tutorial, it seems the concatenation step needs to be revised.

**Comment by bkeyvani** [comment]
You can also specify the order in which you like your source files to be processed and gulp will follow that order:

e.g.
I modified my `path` object as follows, since I have a file named `main.js` and that needs to be processed (concatenated, and uglifyed) before `parent.js` and `child.js`.

```
var path = {
  HTML: 'src/index.html',
  ALL: ['src/assets/js/main.js', 'src/assets/js/*.js', 'src/assets/js/**/*.js', 'src/index.html'],
  JS: ['src/assets/js/main.js', 'src/assets/js/*.js', 'src/assets/js/**/*.js'],
  MINIFIED_OUT: 'build.min.js',
  DEST_SRC: 'dist/src',
  DEST_BUILD: 'dist/build',
  DEST: 'dist'
};
```

I believe If you do not specify your files in the array and just rely on `['*.js']` gulp will process all the `.js` files in that path in alphabetical order.

**Comment by alayek** [comment]
Thanks. Yes, It was my first time with Gulp, so I didn't know these idiosyncrasies. Anyway, I figured out the problem later. Thanks again.

The issue has been rightly closed.

**Comment by peter-houck** [comment]
Another thanks.  Saved me some time.   In the tylermcginnis tutorial you actually need to specify Child, then Parent:

`var path = {
    HTML: 'src/index.html',
    ALL: ['src/js/*.js', 'src/js/**/*.js', 'src/index.html'],
    JS: ['src/js/Child.js', 'src/js/Parent.js', 'src/js/*.js', 'src/js/**/*.js'],
    MINIFIED_OUT: 'build.min.js',
    DEST_SRC: 'dist/src',
    DEST_BUILD: 'dist/build',
    DEST: 'dist'
};`
