### ISSUE TITLE
missing files after uglifying JS IIFE

### ISSUE THREAD

**Issue by cyberkatze** [terinjokes/gulp-uglify#145]
Hi,

I use gulp-task in my build-script:
```javascript
gulp.task('js:build', function () {
    return gulp.src(path.src.js)
        .pipe(rigger())
        .pipe(sourcemaps.init())
        .pipe(cq_jshint(jshintConfig))
        .pipe(cq_jshint.reporter('jshint-stylish'))
        .pipe(uglify())
        .pipe(sourcemaps.write())
        .pipe(gulp.dest(path.build.js))
        .pipe(reload({
            stream: true
        }));
});
```

js/app.js:
```
//= partials/controllers/LoginController.js
//= partials/app.js
```
both files have IIFE code:
``` javascript
(function(){
    'use strict';

    *** code ***
}());
```

after run task I have in build/app.js only app.js-source from partials-folder, but can't find LoginController.js-source!

what did I do wrong?

**Comment by terinjokes** [comment]
Comment out the `uglify()` line. Do you have both files in the output?

**Comment by cyberkatze** [comment]
after I commented uglify() I can see both files. I think, something wrong with this part on both files
``` javascript
(function(){
    'use strict';
}());
```

**Comment by terinjokes** [comment]
Maybe there's an issue with how `rigger` handles the different line endings on Windows?

I suggest contacting that project. Fill free to comment here if that wasn't the issue.
