### ISSUE TITLE
Issue with Babel, ES6 and Uglify

### ISSUE THREAD

**Issue by lewiswalsh** [terinjokes/gulp-uglify#146]
Here is my gulp task:
```javascript
gulp.task('js', function(){
    return gulp.src(paths.src.js)
        .pipe(babel())
        .pipe(uglify())
        .pipe(gulp.dest(paths.dist.js));
});
```

And here is the error I get if I use any ES6, even a simple `let` statement. If I stick with ES5 everything works fine:
```
events.js:141
      throw er; // Unhandled 'error' event
      ^
Error
    at new JS_Parse_Error (eval at <anonymous> (...\node_modules\gulp-uglify\node_modules\uglify-js\tools\node.js:22:1), <anonymous>:1508:18)
    at js_error (eval at <anonymous> (...\node_modules\gulp-uglify\node_modules\uglify-js\tools\node.js:22:1), <anonymous>:1516:11)
    at croak (eval at <anonymous> (...\node_modules\gulp-uglify\node_modules\uglify-js\tools\node.js:22:1), <anonymous>:2008:9)
    at token_error (eval at <anonymous> (...\node_modules\gulp-uglify\node_modules\uglify-js\tools\node.js:22:1), <anonymous>:2016:9)
    at unexpected (eval at <anonymous> (...\node_modules\gulp-uglify\node_modules\uglify-js\tools\node.js:22:1), <anonymous>:2022:9)
    at semicolon (eval at <anonymous> (...\node_modules\gulp-uglify\node_modules\uglify-js\tools\node.js:22:1), <anonymous>:2042:43)
    at simple_statement (eval at <anonymous> (...\node_modules\gulp-uglify\node_modules\uglify-js\tools\node.js:22:1), <anonymous>:2222:73)
    at eval (eval at <anonymous> (...\node_modules\gulp-uglify\node_modules\uglify-js\tools\node.js:22:1), <anonymous>:2095:19)
    at eval (eval at <anonymous> (...\node_modules\gulp-uglify\node_modules\uglify-js\tools\node.js:22:1), <anonymous>:2055:24)
    at block_ (eval at <anonymous> (...\node_modules\gulp-uglify\node_modules\uglify-js\tools\node.js:22:1), <anonymous>:2335:20)
```

A test js file that is failing:
```javascript
(function(window,document,undefined){
    jQuery(document).ready(function($){
        let test = 5;
    });
})(this, document);
```

**Update**
Tested on Windows 10 and Ubuntu 14.04 both with Node 4.1.2

**Comment by loris** [comment]
I do confirm the issue (babel 6+)

**Comment by loris** [comment]
@lewiswalsh to solve this you need to use the es2015 preset from babel (https://babeljs.io/docs/plugins/preset-es2015/)

**Comment by terinjokes** [comment]
As noted above by @loris, this would be resolved by needing to use the es2015 Babel plugin.

I'll happily accept a pull request adding this as an example recipe. :cake:

**Comment by HyperBrain** [comment]
IMHO the use of the es2015 preset is not a proper workaround when targeting Node 4 as code will be transpiled to ES5 and not ES6! Are there any plans to reopen this task or add the proper functionality?

**Comment by yuricamara** [comment]
I agree with @HyperBrain since I want to use ES6 code in some cases.

**Comment by yuricamara** [comment]
Nice @HyperBrain . It worked with uglify-js-harmony! Thank you very much!

**Comment by HyperBrain** [comment]
@yuricamara Thanks belong to @terinjokes :-) He made clear what to do in the REAME.

**Comment by yuricamara** [comment]
Thanks @terinjokes. But, It think it needs to mention there, that uglify-js-harmony works with ES6. I will suggest an update through a PR.

**Comment by dtturcotte** [comment]
@terinjokes can you provide an example of how to use **uglify-js-harmony** with **piping** or **pump**?

For example, this is my gulp task. I am using uglify within the pump but am getting error 

> TypeError: Cannot read property 'match' of undefined

`gulp.task('scripts-prod', function (cb) {
  pump([
        gulp.src(paths.vendorJavascript.concat(paths.appJavascript, paths.appTemplates)),
        plugins.if(/html$/, buildTemplates()),
        plugins.concat('app.js'),
        plugins.ngAnnotate(),
        UglifyJS.minify(),
        plugins.rev(),
        gulp.dest(paths.distJavascript),
        plugins.rev.manifest({path: 'rev-manifest.json'}),
        gulp.dest(paths.distJavascript)
    ],
    cb
  );
});`

**Comment by terinjokes** [comment]
@dtturcotte `uglify-js-harmony` hasn't been updated in 9 months, so it's pretty old. If you're using `gulp-uglify` version 2.0.0, I think you're going to have to downgrade to the last 1.x release: the API I'm calling in UglifyJS changed a few months ago (thus why there was a major version bump).

**Comment by dtturcotte** [comment]
@terinjokes  okay I decided to transpile using 

```
    .pipe(babel({
        presets: [es2015]
    }))
```

Then

` .pipe(babelminify())`


```
var babel  = require('gulp-babel');
var es2015 = require('babel-preset-es2015');
var babelminify = require('gulp-babel-minify');
...
gulp.task('scripts-dev', () => {
  return gulp.src(paths.vendorJavascript.concat(paths.appJavascript, paths.appTemplates))
    .pipe(plugins.if(/html$/, buildTemplates()))
    .pipe(babel({
        presets: [es2015]
    }))
    .pipe(babelminify())
    .pipe(plugins.sourcemaps.init())
    .pipe(plugins.concat('app.js'))
    .pipe(plugins.sourcemaps.write('.'))
    .pipe(gulp.dest(paths.tmpJavascript))
    .pipe(plugins.connect.reload());
});
```

This transpiles and minifies the code fine, except I get this error in browser:

`Error: [$injector:nomod] Module 'app' is not available!`

More on this issue here if you can help: http://stackoverflow.com/questions/33821312/how-to-remove-global-use-strict-added-by-babel
