### ISSUE TITLE
Update UglifyJS (2.5.0 is buggy)

### ISSUE THREAD

**Issue by mishoo** [terinjokes/gulp-uglify#148]
We hit [this issue](https://github.com/mishoo/UglifyJS2/issues/861) and I suspect others will too.  I published uglify-js 2.6.0 which addresses it, so you might want to update your package.json.

**Comment by terinjokes** [comment]
@mishoo Thanks. greenkeeper already [sent a PR](https://github.com/terinjokes/gulp-uglify/pull/147) and I've merged for the next release (in the next few minutes).
