### ISSUE TITLE
uglify removes /*@cc_on */ comment when not at start of line

### ISSUE THREAD

**Issue by Nirazul** [terinjokes/gulp-uglify#152]
I have the following snippet:

```
var v = /*@cc_on (function() {switch(@_jscript_version) {case 1.0: return 3; case 3.0: return 4; case 5.0: return 5; case 5.1: return 5; case 5.5: return 5.5; case 5.6: return 6; case 5.7: return 7; case 5.8: return 8; case 9: return 9; case 10: return 10;}})() || @*/ 0;
```

which I'm minifying with following gulp task:

```
// more stuff
    .pipe( uglify({ preserveComments: 'some' }) )
// more stuff
```

The output is:
```
var t=0;
```

The expected behaviour is to leave the whole comment alone, even if it's not at the start of a new line. It's an inline comment for a reason, after all and should be allowed to stand within other code.
I'm aware that this bug can easily be circumvented by altering my code but I thought it'd be interesting to know.

**Comment by terinjokes** [comment]
The "some" option for "preserveComments" has been deprecated, please try using "license" instead (see the README for details about the differences).

This issue tracker is only for issues with the gulp wrapping of UglifyJS2, this project doesn't implement the minification logic, which includes the handling of comments. If the above does not resolve your issue, please file a new issue on [UglifyJS2](https://github.com/mishoo/UglifyJS2).

Also note this snippet from the UglifyJS2 [documentation](https://github.com/mishoo/UglifyJS2#keeping-copyright-notices-or-other-comments):

> Note, however, that there might be situations where comments are lost. For example:

> ```javascript
function f() {
    /** @preserve Foo Bar */
    function g() {
      // this function is never called
    }
    return something();
}
```

>Even though it has "`@preserve`", the comment will be lost because the inner function g (which is the AST node to which the comment is attached to) is discarded by the compressor as not referenced.

>The safest comments where to place copyright information (or other info that needs to be kept in the output) are comments attached to toplevel nodes.

**Comment by Nirazul** [comment]
Thanks for your help. I'll post my solution if anybody stumbles over this issue in the future:

```
.pipe( 
    uglify({
        preserveComments: function(node, comment) {
            // checks for `@cc_on (IE conditional comment)` and `!` (important comments)
            var checker = /(^@cc_on.*@|^!.*)/i;
            return !!checker.test(comment.value);
        }
    })
)
```

**Comment by terinjokes** [comment]
cc_on is included in the regex for the 'license' option, you shouldn't need
to write your own function.

**Comment by Nirazul** [comment]
I honestly don't think that a thing like `cc_on` should be included in a regex that is described by looking for licence information.

**Comment by terinjokes** [comment]
It's included solely because people expect it to remain in the output, as
its part of the program.
