### ISSUE TITLE
Why the line end symbol is a comma?

### ISSUE THREAD

**Issue by MinonHeart** [terinjokes/gulp-uglify#157]
source code ↓↓↓
```
(function () {
    hello('JavaScript');
    function hello(str) {
        console.log(str);
        console.log(10);
    }
})();
```

gulp-uglify ↓↓↓
```
!function(){function hello(str){console.log(str),console.log(10)}hello("JavaScript")}();
```

UglifyJS2 (npm, uglify-js) ↓↓↓
```
(function(){hello("JavaScript");function hello(str){console.log(str);console.log(10)}})();
```

---
![capture](https://cloud.githubusercontent.com/assets/8586286/12203894/49054508-b66c-11e5-89c2-1462146637c0.png)

1. should be use semicolon;
2. not necessary

⊙﹏⊙!

**Comment by terinjokes** [comment]
I don't know. Please ask UglifyJS2. I don't set it.

**Comment by MinonHeart** [comment]
```
//Javascript
var global;

(function () {
    var str = 'string';
    global = 'global';
})();
```

```
//Compressed
//I am not sure whether it may cause some problems
var global;!function(){var str='string',global='global'});
```

**Comment by terinjokes** [comment]
In that case, it save 4 characters from your output. It it chose a semicolon it would have to repeat `var `.

**Comment by MinonHeart** [comment]
I have updated the above two comments.
The problem may not be serious but its compression mode is different from UglifyJS2.

**Comment by MinonHeart** [comment]
```
var gulp = require("gulp");
var uglify = require("gulp-uglify");

gulp.task("uglify", function () {
    return gulp
        .src("test.js")
        .pipe(uglify({
            compress: false,
            mangle: false
        }))
        .pipe(gulp.dest("./test.min.js"))
})
```

It will act like UglifyJS2 if `compress set to false`.

**Comment by MinonHeart** [comment]
I think `compress should set to default value: false`, because UglifyJS2 is disable `compress` unless user add parameter `--compress`(`-c`).
