### ISSUE TITLE
Streaming not supported

### ISSUE THREAD

**Issue by stevenvachon** [terinjokes/gulp-uglify#159]
https://github.com/hughsk/vinyl-source-stream/issues/1

**Comment by terinjokes** [comment]
From the gulp [Plugin Guidelines](https://github.com/gulpjs/gulp/blob/master/docs/writing-a-plugin/guidelines.md) (emphasis mine):

> 9\. The type of file.contents should always be the same going out as it was when it came in
>  * If file.contents is null (non-read) just ignore the file and pass it along
>  * If file.contents is a Stream and you don't support that just emit an error
>    * **Do not buffer a stream to shoehorn your plugin to work with streams.** This will cause horrible things to happen.

The upstream module [UglifyJS2](https://github.com/mishoo/UglifyJS2) does not support streaming. In fact, no Node.js JavaScript minifier supports streaming.

As the end user, you can opt into buffering. I personally prefer [`vinyl-buffer`](https://github.com/hughsk/vinyl-buffer), but [`gulp-streamify`](https://github.com/nfroidure/gulp-streamify) is another alternative.

**Comment by stevenvachon** [comment]
Is it not the responsibility of this package to ensure that it works with gulp?

**Comment by terinjokes** [comment]
This package works with gulp. JavaScript files are minified when `file.content` is a Buffer. Per the guidelines, I don't buffer streams to make them work with UglifyJS2.

**Comment by stevenvachon** [comment]
What's the difference between manually and automatically buffering streams?

**Comment by robwierzbowski** [comment]
Automatically buffering the stream in gulp-uglify would silently change the data that's being sent through the pipes, potentially causing unexpected behaviors further along. I think it's more in line with gulp's principles for the user to change to a buffer explicitly.
