### ISSUE TITLE
No mangle function names

### ISSUE THREAD

**Issue by cliren** [terinjokes/gulp-uglify#161]
Passing the following options as per a previous issue suggestion is still mangling the function names. Is there support to pass the following uglifyjs option ?

-nmf or --no-mangle-functions – in case you want to mangle variable names, but not touch function 
names.

```
.pipe(uglify({
      mangle: {keep_fnames: true}
    }))

```

**Comment by terinjokes** [comment]
It looks like you need to pass `keep_fnames` to both `mangle` and `compress`.
