### ISSUE TITLE
uglify js change break code logic 

### ISSUE THREAD

**Issue by omarazmi** [terinjokes/gulp-uglify#162]
when trying to uglify js, it is break the code and covert it to buggy code:
my original coded :
`var wnow = (function (_w) {
	'use strict';
    var W = _w.Worldnow || {}
        , Page = (_w.wn || {}).page || {}
	var Helpers = {
        debug: function(message, timer, type) {
            if((((Page || {}).build || {}).version || '') == 'Local-Debug') {
                var logMethod = (type == 'error') ? console.error : console.log;
                logMethod('Notice from wnow.Helpers.debug =====================');
                if(timer) {
                    var timers = window.DEBUG_TIMERS || []
                    if(timers.indexOf(timer) > -1) {
                        logMethod('Timer ' + timer + ' ended. ' + message);
                        console.timeEnd(timer);
                    } else {
                        timers.push(timer);
                        logMethod('Timer ' + timer + ' started. ' + message);
                        console.time(timer);
                    }
                    window.DEBUG_TIMERS = timers;
                } else {
                    logMethod(message);
                }
                logMethod('========================================================');
            }
        }
	}
	W.Helpers = Helpers
	return W
})(window);
`

and output is:

`var wnow=function(e){"use strict";var o=e.Worldnow||{},r=(e.wn||{}).page||{},n={debug:function(e,o,n){if("Local-Debug"==(((r||{}).build||{}).version||"")){var i="error"==n?console.error:console.log;if(i("Notice from wnow.Helpers.debug ====================="),o){var d=window.DEBUG_TIMERS||[];d.indexOf(o)>-1?(i("Timer "+o+" ended. "+e),console.timeEnd(o)):(d.push(o),i("Timer "+o+" started. "+e),console.time(o)),window.DEBUG_TIMERS=d}else i(e);i("========================================================")}}};return o.Helpers=n,o}(window);`

see this 

> if(i("Notice from wnow.Helpers.debug ====================="),o)

if statement take 2 parameters after uglifying ?

**Comment by terinjokes** [comment]
This seems fine, there's no change in behavior exhibited here. The test of the if expression is a sequence expression and the last member of a sequence expression is what is tested for truey- or falsey-ness.

I'd have to dig into UglifyJS to determine why it decided to transform into this, but it's valid and doesn't change semantics.

**Comment by omarazmi** [comment]
thanks for your reply, 

but the javascript if statement doesn't take more than one expression , try to debug that in console, or try to find any documentation like [MDN](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Statements/if...else#Syntax).

**Comment by terinjokes** [comment]
@omarazmi: looking at it here, the illegal invocation is that `console.log` and `console.error` aren't being bounded when assigned to `logMethod`.

If you don't care about old IE, you can use `Function.prototype.bind` to bind the context to `console` when you assign to the variable.

**Comment by omarazmi** [comment]
ok, thanks for your help .
