### ISSUE TITLE
The uglify 'warning' output is missing filename

### ISSUE THREAD

**Issue by erwinw** [terinjokes/gulp-uglify#163]
The uglify 'warning' option throws useful messages to console.error. Unfortunately, it does so without filename information. If you're uglifying a bunch of files, that's a real drag.

**Comment by terinjokes** [comment]
We should probably ask the UglifyJS project to hand us the warnings so that we can do something with them.

**Comment by erwinw** [comment]
Good point. In the mean time, as you might've seen, I've put in a PR (#164) for your consideration.

**Comment by terinjokes** [comment]
Opened mishoo/UglifyJS2#958.

**Comment by terinjokes** [comment]
In version 3, UglifyJS now passes the warnings back to the caller of the API, so I'll now be able to handle it in a better fashion. I haven't decided how I'll do so yet, but tagging this ticket for the next major release.

**Comment by terinjokes** [comment]
@erwinw On the "three" branch, I'm logging the warnings (along with the filename) to the gulp logger. I think this preserves the behavior expected, without requiring a separate gulp plugin to print them (like the eslint gulp plugins).

Please give it a shot and let me know what you think. In the meantime, I'm closing this ticket, as I think the work is done and awaiting release.
