### ISSUE TITLE
Updating UglifyJS 2 to 2.6.1

### ISSUE THREAD

**Issue by danduh** [terinjokes/gulp-uglify#165]
Currten version of UglifyJS 2 dose not support any of ECMA6 features. 
Update UglifyJS 2 ro 2.6.1 will actually add some of it. 

Thanks,

**Comment by terinjokes** [comment]
@danduh: you need to update the version of gulp-uglify you're using. We've been at 2.6.1 for a month now.

**Comment by danduh** [comment]
@terinjokes, Hi, and thank you for respond. 
Tag v 1.5.1
https://github.com/terinjokes/gulp-uglify/blob/v1.5.1/package.json
 "uglify-js": "2.6.0",
Do I miss somethig?

**Comment by terinjokes** [comment]
Nope. Try again in 5 minutes.

**Comment by terinjokes** [comment]
Bumped in v1.5.2
