### ISSUE TITLE
uglify doesn't work for base64.js

### ISSUE THREAD

**Issue by alexhu01** [terinjokes/gulp-uglify#167]
before uglify: 
var re_btou = new RegExp([
        '[\xC0-\xDF][\x80-\xBF]',
        '[\xE0-\xEF][\x80-\xBF]{2}',
        '[\xF0-\xF7][\x80-\xBF]{3}'
    ].join('|'), 'g');

after uglify:

p=new RegExp(["[À-ß][-¿]","[à-ï][-¿]{2}","[ð-÷][-¿]{3}"].join("|"),"g")

**Comment by terinjokes** [comment]
You need to set the "ascii: true" option. If you think this is a real bug,
please file it against UglifyJS2.
