### ISSUE TITLE
Uglify not working with Angular2 stack

### ISSUE THREAD

**Issue by carnun** [terinjokes/gulp-uglify#168]
Please see my [recent post on SO](http://stackoverflow.com/questions/35612100/angular2-ngif-not-working-in-deployment-environment/35636715#35636715) about what I experienced. It took me a while to figure out that it had to do with the mangling via gulp-uglify.

In order to recreate the issue clone this code - https://github.com/sudoorgza/my-words/tree/uglify-mangle-issue. Then do an "npm install", run "gulp build" then deploy the code in the "dist/" folder to your favourite webserver.

**Comment by pitops** [comment]
thank you this was helpful!

**Comment by terinjokes** [comment]
@carnun @pitops I don't control how UglifyJS mangles JavaScript. Please file an issue against the UglifyJS2 project so they can fix it for everyone.
