### ISSUE TITLE
Error: Cannot find module './lib/source-map-generator'

### ISSUE THREAD

**Issue by Hesesses** [terinjokes/gulp-uglify#174]
I opened an old project and getting this error suddenly.. Any ideas how to fix?

```
Error: Cannot find module './lib/source-map-generator'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/hese/node_modules/gulp-uglify/node_modules/uglify-js/node_modules/source-map/source-map.js:6:30)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```

**Comment by terinjokes** [comment]
@Hesesses Looks like your "node_modules" folder is incomplete. Try removing it and run `npm install` again.

**Comment by joeflack4** [comment]
I encountered this issue today as well. On Windows. Was running node 3.something with npm 2.something. I had cloned a repo and done an 'npm install', and was encountering some issues, and install was not successful. 

I just did a straight re-install of node. Now on node 4.6.0 and npm 3.10.8. 

The re-install of node fixed the issues with npm install of node_modules for the cloned repo project. However when I tried to run several gulp commands, I encountered the issues here. I did another nmp install, but that didn't work. Finally I took @terinjokes literally and removed the node_modules completely. Then did a fresh npm install. After that, my gulp commands were working fine.

**Comment by var-che** [comment]
If you can't remove `node_modules` file, you can try this:

Install RimRaf:

`npm install rimraf -g`

And in the project folder delete the node_modules folder with:

`rimraf node_modules`

Then you can go and do `npm install` to get the fresh start.

**Comment by CherishTheYouth** [comment]
thank you 
good job 
i will try soon

**Comment by pixiedust57** [comment]
@var-che 
You just saved my career...
Thank you so much

**Comment by chidubemOkafor** [comment]
> @var-che You just saved my career... Thank you so much

lolz
