### ISSUE TITLE
Streaming not supported?

### ISSUE THREAD

**Issue by nmn** [terinjokes/gulp-uglify#178]
```sh
Message:
    /Users/ngoel/Documents/eng-neuak-ui-manage/index.js: Streaming not supported
Details:
    fileName: /Users/ngoel/Documents/eng-neuak-ui-manage/index.js
    domainEmitter: [object Object]
    domain: [object Object]
    domainThrown: false
```

Tried on a browserify bundle and gulp.src. Same error both ways.

**Comment by terinjokes** [comment]
Hello @nmn. This plugin doesn't support streaming Vinyl instances, as UglifyJS2 doesn't support streams. Please use [`vinyl-buffer`](https://www.npmjs.com/package/vinyl-buffer) before `gulp-uglify`.

Docs PR welcome.

**Comment by nmn** [comment]
Oh `vinyl-buffer` wish I'd thought of that! I'll give you a PR in a bit.
