### ISSUE TITLE
Uglify throws Parse error 

### ISSUE THREAD

**Issue by McVanS** [terinjokes/gulp-uglify#185]
Ran into the same problem as others and after two days discovered the problem. Turns out the error was not a typo but caused by "Unexpected token: operator (>)" and the code turned out to be: workingFiles.find(x => x.selectedFile == selectedFiles[i].name). I remove the > and the file passes. This is a problem but I didn't see anyone else mentioning it. At this point I’m removing the > character and uglifying then editing the > back into the uglified file. It’s a real pain and sure to cause confusion and errors in the future.

**Comment by terinjokes** [comment]
Please see the README for instructions on how to use the alpha ES6 support,
or use Babel to transform to ES5.

**Comment by danactive** [comment]
@terinjokes Which [README.md](README.md)? I don't see ES6 mentioned...

**Comment by terinjokes** [comment]
@danactive The very bottom, [right about here](https://github.com/terinjokes/gulp-uglify#using-a-different-uglifyjs)

**Comment by danactive** [comment]
Ah thx

**Comment by McVanS** [comment]
Thanks.
