### ISSUE TITLE
Fails when using default parameters in functions

### ISSUE THREAD

**Issue by WandertVanDerHertz** [terinjokes/gulp-uglify#189]
gulp-uglify fails when (I think) it shouldn't. It fails to uglify functions with default parameters which is allowed since ecmascript6.

```
function functionTest(parameterTest=false){
    // This fails with gulp-uglify but jshint just warns that default values for function's parameters are
    // only allowed since ecmascript6   
}
```

**Comment by terinjokes** [comment]
@WandertVanDerHertz This project is just a wrapper around [UglifyJS2](https://github.com/mishoo/UglifyJS2), which is responsible for the actual compression. See the instructions [the README](https://github.com/terinjokes/gulp-uglify#using-a-different-uglifyjs) for attempting to use alpha ES6 support and track [this UglifyJS2 issue](https://github.com/mishoo/UglifyJS2/issues/448) for when they'll merge ES6 support.
