### ISSUE TITLE
Compressor options not honored

### ISSUE THREAD

**Issue by wheatbrad** [terinjokes/gulp-uglify#194]
The ability to set options does not seem to be working. Perhaps I'm not passing the obj correctly? I've tried many options, without success, to see if the output would respond.

Here is my task:

```
gulp.task('js', function (cb) {
    pump([
        gulp.src('./js/app.js'),
        gulpBrowser.browserify(),
        babel({ presets: ['es2015'] }),
        uglify({compressor: { unused: false } }).on('error', function(e) {
            console.log(e);
        }),
        gulp.dest('../public/js/')
    ]);
});
```

Similar to issue #133 opened by @MarioHofer — not sure if this was ever corrected before being closed.

**Comment by terinjokes** [comment]
Thanks for using gulp-uglify 💖 !

The compressor options are provided via the `compress` property (not `compressor`).

Also, if you pass the callback to pump (as shown in the README) you don't need to attach an error handler.

```javascript
gulp.task('js', function (cb) {
    pump([
        gulp.src('./js/app.js'),
        gulpBrowser.browserify(),
        babel({ presets: ['es2015'] }),
        uglify({compress: { unused: false } }),
        gulp.dest('../public/js/')
    ], cb);
});
```

**Comment by wheatbrad** [comment]
@terinjokes **thanks!** I thought I might be doing something wrong

**Comment by terinjokes** [comment]
@wheatbrad No worries. I'm happy to make changes to documentation to make them clearer if you have any particular things I should review.
