### ISSUE TITLE
Uglify throws an error when using '`'

### ISSUE THREAD

**Issue by phpfs** [terinjokes/gulp-uglify#197]
Hello!

I use \` (replaced with ? in error log {Github doesn't like it either!}) for multi-line text in JS, but gulp-uglify doesn't seem to like it :(

`Error: /-----min.js: Unexpected character '?']
  message: '/-----min.js: Unexpected character \'?\'',
  fileName: '/-----min.js',
  lineNumber: 16802,
  stack: 'Error\n    at new JS_Parse_Error (...)`

Here's a code example that seems to cause this issue:
> var text = \`<div onclick="runMe('V1'); return false;"...\`;

Thanks for your help :)

**Comment by terinjokes** [comment]
Thanks for using `gulp-uglify` 💖 !

The currently releases version of UglifyJS doesn't support any ES6 or later language features. The UglifyJS project is working hard on adding them.

You can still use template strings, you just must first convert them to ES5 code, such as by using Babel.

Hopefully this helps, if not fill free to leave a comment.

**Comment by phpfs** [comment]
Hello :)

Which Babel Preset should I use?

Thank you!

-Looking forward to es6 in UglifyJS :)

**Comment by phpfs** [comment]
Found it: es2015

Thanks and keep up your work :)
