### ISSUE TITLE
Unexpected character '`'

### ISSUE THREAD

**Issue by adam1920** [terinjokes/gulp-uglify#200]
I get error: "  Unexpected character '`' ".

This is my gulp script:
`
var uglify      = require('gulp-uglify');
var pump        = require('pump');

gulp.task('compress', function (cb) {
  pump([
        gulp.src('js/all.js'),
        uglify(),
        gulp.dest('dist')
    ],
    cb
  );
});`

Please help!!

**Comment by adam1920** [comment]
I found solution with 'gulp-babel' [here](http://stackoverflow.com/questions/34398338/uglification-failed-unexpected-character)

**Comment by jamesbondo** [comment]
I posted the question on stackoverflow then i thought of here...
Here's the link
http://stackoverflow.com/questions/39657041/compile-angular-1-5-component-code-with-gulp-uglify-minify-not-working-when-the
