### ISSUE TITLE
Version 2.0.0 release logs and build

### ISSUE THREAD

**Issue by laurent-le-graverend** [terinjokes/gulp-uglify#201]
The v2.0.0 has been released in NPM, it looks a bit hazardous to update.

1/ The changelog is missing the release notes:
https://github.com/terinjokes/gulp-uglify/blob/master/CHANGELOG.md

2/ The dependency-ci test failed:
https://dependencyci.com/github/terinjokes/gulp-uglify/builds/11
https://github.com/terinjokes/gulp-uglify/commits/master

**Comment by Riim** [comment]
👍

**Comment by terinjokes** [comment]
Release Notes were moved to GitHub Releases. I'll add a note. Dependency CI failed outside my control, and is safe to ignore.

**Comment by terinjokes** [comment]
Resolved in 2d4c9fced7cf430990fc91e7c716a0a994cca7cd.
