### ISSUE TITLE
ECMA6 Support

### ISSUE THREAD

**Issue by ivanstan** [terinjokes/gulp-uglify#207]
Would be nice to support ecma6 in future, currently when I tried to minimize es6 class I recieve an error

```
events.js:160
      throw er; // Unhandled 'error' event
      ^
GulpUglifyError: unable to minify JavaScript
Caused by: SyntaxError: Unexpected token: name (<ClassName>) (line: 10931, col: 6, pos: 987241)```

**Comment by terinjokes** [comment]
The included version of UglifyJS doesn't yet support ES6, you can follow directions in the README along with the `harmony` branch of UglifyJS to minify them.
