### ISSUE TITLE
Angular2 App no longer works after uglify

### ISSUE THREAD

**Issue by buddyackerman** [terinjokes/gulp-uglify#208]
I have an app that I've been working on since RC2 and when I recently switched to RC5 it no longer works after I uglify it.  I get template parse errors in all of my PrimeNG controls where I specify an attribute in the markup.  The code was not significantly modified other than to add an NgModule as the bootstrap target.  The app works fine when run in a non-bundled/minified mode.

**Comment by terinjokes** [comment]
@buddyackerman I don't use Angular, but I know in Angular 1 to minify you had to use a tool to change dependency injections before minification. Are you using anything before `gulp-uglify` to do this?

**Comment by buddyackerman** [comment]
I'm using browserify to bundle the javascript then using uglify to compact it.  Here's my task.

`gulp.task('bundleAppJS', function () {
    return browserify(['./app/app.js']).bundle()
        .pipe(vinylsource('bundle.min.js'))
        .pipe(vinylbuffer())
        .pipe(uglify())
        .pipe(gulp.dest('./lib'));
});
`

**Comment by terinjokes** [comment]
@buddyackerman does `gulp-ng-annotate` (as described here: https://github.com/terinjokes/gulp-uglify/issues/60#issuecomment-66268180) help?

**Comment by buddyackerman** [comment]
That didn't help.  Still getting the same error.

**Comment by jamesbondo** [comment]
I posted the question on stackoverflow then i thought of here...
Here's the link
http://stackoverflow.com/questions/39657041/compile-angular-1-5-component-code-with-gulp-uglify-minify-not-working-when-the

**Comment by buddyackerman** [comment]
@jamesbondo The issue you posted is different from the one discussed here.  My issue was actually caused by a bug in NG2 RC5 [@angular/#10618](https://github.com/angular/angular/issues/10618).

**Comment by terinjokes** [comment]
@buddyackerman Does this mean this issue is now resolved and I can close this issue?

**Comment by buddyackerman** [comment]
@terinjokes yes, it was an Angular issue
