### ISSUE TITLE
Support IE8

### ISSUE THREAD

**Issue by checkphi** [terinjokes/gulp-uglify#214]
uglify-js made a change in their default behavior from version 2.6.4 to 2.7.0. From now on IE8 is not supported anymore, but there is no possiblity in gulp-uglify to pass the "--support-ie8" flag.

Please add this option.

**Comment by terinjokes** [comment]
You can pass `false` to all the "screw_ie8" options for the same behavior as `--support-ie8` flag.

```javascript
{
  compress: { screw_ie8: false },
  mangle: { screw_ie8: false },
  output: { screw_ie8: false }
}
```

There's ongoing work to better match the API interface with the CLI tool that may improve this in the future. PR to add a articles to the docs section accepted. :)

**Comment by Worthy7** [comment]
Hi, I tried this, didn't work...

**Comment by Worthy7** [comment]
FYI for anyone else who comes here, it has been changed and must be written like so:
`.pipe(uglify({ie8:true}))`

**Comment by wslx520** [comment]
@Worthy7 good, thank you very much!
