### ISSUE TITLE
preserveComments: "license" not working

### ISSUE THREAD

**Issue by bigteejay** [terinjokes/gulp-uglify#215]
**LICENSE.txt**
```
/* Copyright (C) Organization, Inc - All Rights Reserved
 * Blah blah blah 
 * More Blah blah blah 
 * Written by: <%= pkg.author %> 
 */
```

**gulpfile.js** (excerpt)
```js
var pkg = require("./package.json"),
var norefs = "!" + paths.scripts.src + "_references.js";

gulp.task("min:scripts", function () {
    return gulp.src([paths.scripts.src], { base: "." })
        .pipe(flatten())
        .pipe(header(
            fs.readFileSync('LICENSE.txt'),
            {
                pkg: pkg
            }
        ))
        .pipe(gulp.dest(paths.scripts.dest))
        .pipe(stripdebug())
        //.pipe(uglify({preserveComments: 'license'}))
        .pipe(rename({
            suffix: '.min'
        }))
        .pipe(gulp.dest(paths.scripts.dest));
});
```

With uglify line commented out, I get the license/header in both copies (original and what would be minified version) placed in dest path.  With uglify line uncommented, only original has the license block.  Uglify doesn't appear to respecting the `preserveComments` option.

The comment block (as best as I can tell) passes all three rules for a license block

**Comment by terinjokes** [comment]
Can you email me a file that fails to preserve comments? I want to make
sure it's not a known limitation with UglifyJS2.

**Comment by bigteejay** [comment]
You want the mentioned license file? The js file that is getting the license prepended, or (parts of) the gulpfile generating the output?

**Comment by bigteejay** [comment]
Also, realized this may be relevant (perhaps this is a bug specific to the version I am using).

From my package.json...
`"gulp-uglify": "^1.2.0",`

**Comment by terinjokes** [comment]
Is the license block preserved when passed to the UglifyJS CLI tool? UglifyJS2 doesn't currently claim to preserve all comments, with the following note in their documentation:

> Note that currently not *all* comments can be kept when compression is on, because of dead code removal or cascading statements into sequences.

**Comment by bigteejay** [comment]
Just checked and, it doesn't.

Are there any incantations that would survive?  If not, perhaps documentation should be updated so as to not mislead folks that it is possible?

**Comment by bigteejay** [comment]
Just checked, it doesn't.

Adding @license or @preserve (jsdoc) statements does then retain it however.  

I wonder if I might be able to revive protecting it without this by using a regex that looks for "Copyright" or something to that effect (apparently searching for that is no longer default behavior?)

**Comment by bigteejay** [comment]
It works if I use...
`uglifyjs test.js --comments /Copyright/`

With the same license block in my initial post, and with a js file something similar to the following...

```
//foo
// bar
var x = 1;
```

...the license block is now correctly retained and foo/bar are both correctly removed.

**Comment by bigteejay** [comment]
The comments on this plugin's readme says that it uses [uglify-save-license](https://github.com/shinnn/uglify-save-license) to preserve comments, which in turn indicates that the there should be block passed as such...
`comments: saveLicense`

**Comment by bigteejay** [comment]
My sincere apologies, it is working fine as indicated.

I think I had an old version installed somewhere.  Just installed 2.0 and it runs exactly as documented/described.

**Comment by terinjokes** [comment]
I can't tell you why it doesn't preserve without seeing the file, which you never sent. UglifyJS2 attaches comments to a code block, so if the code is removed or rewritten, it won't be preserved, no matter what you provide as the value to "preserveComments".

The option here works if the conditions specified match AND the code the comment is attached to isn't removed.

**Comment by bigteejay** [comment]
I [asked](https://github.com/terinjokes/gulp-uglify/issues/215#issuecomment-241901943), but you never clarified what you needed.  Again, it was a problem on my end, my apologies for the hassle.

**Comment by terinjokes** [comment]
Sorry, looks like my reply (via email) was lost. I was travelling a bunch last week.

For clarification, I wanted the file after you added the header, but before passed to gulp-uglify. Glad to hear upgrading worked for you.

**Comment by ireeoome** [comment]
I want to leave some special code like /*_lscacher_XXXXXX_lscacher_*/ in my uglified js file,how can i do?
preserveComments:/\/\*_lscacher_XXXXXX_lscacher_\*\//gi
doesnt work.please help me~thank u
