### ISSUE TITLE
Continue stream with non-minified file on error

### ISSUE THREAD

**Issue by jongunter** [terinjokes/gulp-uglify#216]
If there is a parse error, is it possible to have this plugin ignore it and pass the non-minified file down the stream (rather than the minified file)? 

The minifier in Microsoft's MVC framework has been able to do this for a while now.

**Comment by terinjokes** [comment]
No, this functionality isn't built into `gulp-uglify`. However, since `gulp-uglify` simply exposes a Node.js Stream API, you can wrap the stream to add this functionality.
