### ISSUE TITLE
Uglify doesn't seem to do anything (probably my own fault)

### ISSUE THREAD

**Issue by nicohvi** [terinjokes/gulp-uglify#218]
Hiya!

When I transpile my javascript the end result looks exactly the same whether I run it through `gulp-uglify` or not (i.e. the code isn't minified) - anything obvious I'm doing wrong here?

```javascript
const uglify = require('gulp-uglify');
function build () {
        const bundler = browserify(opts);
        bundler.transform(babelify);
        bundler
        .bundle()
        .on('error', handleErrors)
        .pipe(source('app.js'))
        .pipe(gulp.dest(dest))
        .pipe(buffer())
        .pipe(uglify()) // nothing happens to the output when I remove this line
        .on('end', build ? () => revision('js') : noop)
    }
```

**Comment by mikaelbr** [comment]
Uglify only transforms the actual content of the stream, not the contents of the files. You should have uglify in the pipeline before `gulp.dest()` as you want the uglified output saved to the destination file.

**Comment by nicohvi** [comment]
Thanks @mikaelbr, you're the best. Better than all the rest

**Comment by terinjokes** [comment]
@nicohvi If you follow the advice in [Why Use Pump?](https://github.com/terinjokes/gulp-uglify/blob/master/docs/why-use-pump/README.md#why-use-pump) you'll be correctly handling the errors for all tasks in your pipeline.
