### ISSUE TITLE
Two Server unlify diff two file

### ISSUE THREAD

**Issue by zhailei31665431** [terinjokes/gulp-uglify#220]
Source code 
```
String.prototype.encodeReg=function(){
	return this.replace(/([.*+?^=!:${}()|[\]/\\])/g,'\\$1');
}
```

<img width="680" alt="2016-09-22 19 46 01" src="https://cloud.githubusercontent.com/assets/3082395/18746990/42a4198a-80fd-11e6-9998-7bc4f2512a4d.png">

**Comment by zhailei31665431** [comment]
<img width="705" alt="2016-09-22 19 47 58" src="https://cloud.githubusercontent.com/assets/3082395/18747023/7cd4657e-80fd-11e6-9011-41dcc33c4f1a.png">

**Comment by terinjokes** [comment]
Please file bugs about minification with the [UglfyJS2](https://github.com/mishoo/UglifyJS2) project.
