### ISSUE TITLE
Question: how to avoid uglifying certain files

### ISSUE THREAD

**Issue by rbatllet** [terinjokes/gulp-uglify#224]
Hello, 

I've a vendor module that if I uglify it, it stops working.

How to skip this vendor module to be modified?

My gulp task is:

```
gulp.task('compress:assets', () => {
  return gulp.src(`${appConfig.app}/index.html`)
    .pipe(useref())
    .pipe(uglify())
    .pipe(gulp.dest(appConfig.dist));
});

For example, a vendor module like: "bower_components/myModule/dist/myLibrary.js"

```

**Comment by terinjokes** [comment]
You can use a tool, such as [`gulp-if`](https://github.com/robrich/gulp-if) to ignore certain files. If you need help integrating, please open a question StackOverflow with and tag it with `gulp`.
