### ISSUE TITLE
Mangle option breaks file with non-ascii names

### ISSUE THREAD

**Issue by emersonthis** [terinjokes/gulp-uglify#227]
I'm using gulp-uglify v2.0 with an AngularJS 1.x project and it works great IF I pass the option to turn OFF mangle. Here's my exact task:

``` javascript
gulp.task('build:js', function() {
    var concat = require('gulp-concat');
    var uglify = require('gulp-uglify');
    return gulp.src(config.js.src)
        .pipe(concat(config.js.concat))
        .pipe(uglify({mangle:false})) // absence of this option is causing invalid characters        .pipe(gulp.dest(config.js.dest))
});
```

If I remove `{mangle:false}` the task still runs without throwing any errors. But when I try to load pages in the browser that use that javascript file... they don't. Weirdly, there are also no errors in the console.

Any ideas what I'm doing wrong?

**Comment by terinjokes** [comment]
You should pass the `ascii_only` beautify option:

```javascript
var opts = {
  "beautify": {
    "ascii_only": true
  }
};
```

Alternative, ensure the JavaScript files are being served with the correct Content-Type header that includes the encoding.
