### ISSUE TITLE
Renaming minified file after uglify also changes the source-reference in source map

### ISSUE THREAD

**Issue by allansson** [terinjokes/gulp-uglify#23]
I am using the following Gulp-task:

```
var concat = require('gulp-concat');
var rename = require('gulp-rename');
var uglify = require('gulp-uglify');

gulp.task('package', function () {
    return gulp.src('./src/**/*.js')
            .pipe(concat('myfile.js'))
            .pipe(gulp.dest('./dist/'))
            .pipe(uglify({ outSourceMap: true }))
            .pipe(rename(function (path) {
                if(path.extname === '.js') {
                    path.basename += '.min';
                }
            }))
            .pipe(gulp.dest('./dist/'));
});
```

I was expecting this to generate a source map for the minified file, referencing the concatenated file 'myfile.js' in the sources-array of the source map, i.e.

```
{
    "version": 3,
    "file": "myfile.min.js.map",
    "sources": ["myfile.js"] // <-- This here
    /* SNIP */
}
```

However, the file referenced is the renamed minified file, i.e. "myfile.min.js". I am not sure if this behavior is intended or not. The reason appears to be that when calling this.push for the minified content all other pipes in the chain are executed synchronously, thus changing the file.relative-property of the file before the source map file is created. I've managed to fix this issue in two different ways, and I am not sure which would be preferrable:
- Output a new file with the mangled code instead of changing the contents of the existing, so that file.relative never changes. The source map file generates its filename from the newly created file, but adds the old file as a source.
- Cache the filename before calling this.push, and use the cached name in the sources-array.

I could easily make a pull request with a fix, but I would like some input before I do anything.

**Comment by furbano1988** [comment]
Thanks man! Thank so much.
