### ISSUE TITLE
preserveComments: 'license' not working as expected

### ISSUE THREAD

**Issue by alvarotrigo** [terinjokes/gulp-uglify#234]
I noticed when using `preserveComments: 'license'` it doesn't remove comments containing the string `license` in it.

Contrary to what the documentation states:

> 1.  The comment is in the first line of a file.
> 2. The regexp for license statement matches the string of the comment. It matches, for example, MIT and Copyright.
> 3. There is a comment at the previous line, and it matches 1. 2. or 3.

``` javascript
        .pipe(uglify({
            preserveComments: 'license'
        }))
```

Comments like this won't be removed:

``` javascript
// this is unlicensed
// be careful with the license here
```

As the documentation for [uglify-save-license has a broken link](https://github.com/shinnn/uglify-save-license/issues/3).
It is not clear enough for me how the `preserveComments` parameter works.

I tried **without success** to use another string in it, such as `MIT` or `Copyright` in order to match the following license comment:

``` javascript
/*!
 * demo
 * https://github.com/demo
 * @license MIT licensed
 *
 * Copyright (C) 2015 
 */
```

**Comment by SebastianS90** [comment]
If you want to preserve some comments, then `preserveComments` actually should be a function as specified in the readme of this module.
The plain string `'license'` is just a shortcut for `require('uglify-save-license')` such that you will use the [function exported by the uglify-save-license module](https://github.com/shinnn/uglify-save-license/blob/e8abfd7ed08ae8298b9d2e719448b047924ca91a/index.js#L14).

So specifying a regex string does not work. But you can provide any custom function that fulfills your needs, just look at the function linked above for an example.

If you want to customize the behavior of `uglify-save-license`, then you can do the following:
* fork the `uglify-save-license` repository, create a branch `my_customization` and customize the `index.js` file there (e.g. edit the regex there)
* in your `package.json` file, use your own fork of `uglify-save-license`:
````javascript
{
  // ...
  "dependencies": {
    // ...
    "uglify-save-license": "https://github.com/alvarotrigo/uglify-save-license/tarball/my_customization"
  }
}
````
* use your customized module to preserve comments:
````javascript
        .pipe(uglify({
            preserveComments: require('uglify-save-license')
        }))
````

**Comment by terinjokes** [comment]
The behavior here seems correct: `uglify-save-license` has a small regex that matches comment text that should be kept.
