### ISSUE TITLE
uglified code not working with new nodejs

### ISSUE THREAD

**Issue by gengshenghong** [terinjokes/gulp-uglify#242]
I've upgraded my node to a new version, and found the same uglified code not working. 
new version: node-v6.9.1-linux-x64
old version: node-v5.12.0-linux-x64

The simple code to reproduce:
The original code:
if (true) { const child_process=require('child_process'); }

uglified:
if (true) const child_process=require('child_process');

The uglified code works with old nodejs, but fail with new version. I am not sure why nodejs changed this behavior (any standard changes?). But I wonder if I have a way to make it work, for example, preserver this part of code without uglify?

Looking forward to your comments.

Thanks,
Shenghong

**Comment by terinjokes** [comment]
This looks to be correct, the `const` token is not valid in that location.
