### ISSUE TITLE
Using `pump` fails silently

### ISSUE THREAD

**Issue by Janjuks** [terinjokes/gulp-uglify#245]
I'm not sure if this or `gulp-pump` is the right place for this issue, if this is not, I'm sorry.

Using `uglify` with `pump` fails silently. Had a bunch of js files and one of them had ES6 arrow functions. Instead of throwing error, it just ignores it. Without `pump` the error is thrown.

**Comment by terinjokes** [comment]
Can you show your gulpfile? Did you make sure to pass the callback function into pump? An error is pretty-printed here.

**Comment by Janjuks** [comment]
No, I had not passed the callback function. With callback the error get's printed. Thanks!
