### ISSUE TITLE
IE 11 and reserved words

### ISSUE THREAD

**Issue by neilyoung** [terinjokes/gulp-uglify#250]
Hi,

I'm having an issue with a JS schema object and uglify. The problem is that a schema object I'm using needs to contain an "enum" property

    var x = {
      enum: ["a", "b","c"]
    }

This leads to problems with IE11, which treats "enum" (like "default" and others http://www.w3schools.com/js/js_reserved.asp) as "reserved words". The script execution breaks. One can work around by this notation:

    var x = {
      "enum": ["a", "b","c"]
    }

The problem: This "enum" is reverted to an enum (w/o quotes) after "uglification", which again breaks IE11 script execution. Any idea, how to achieve "enum" in uglified output?

Regards

**Comment by terinjokes** [comment]
Please open a ticket with [UglifyJS](https://github.com/mishoo/UglifyJS2) which is the project that actually does the minification.

**Comment by neilyoung** [comment]
Thanks. Done

**Comment by neilyoung** [comment]
Got this hint:

You could use the beautify option keep_quoted_props=true.

$ echo 'var x = {foo: 3, "enum": ["a", "b"]}' | uglifyjs -b keep_quoted_props=true,beautify=false -m -c
var x={foo:3,"enum":["a","b"]};
This will keep all quoted props unfortunately.

Is there a way to specify this option in a gulp call like 

    .pipe(uglify())

?
