### ISSUE TITLE
Options

### ISSUE THREAD

**Issue by MasterOfZozo** [terinjokes/gulp-uglify#253]
In options section of readme are links to [lisperator.net](http://lisperator.net)
But UglifyJS have now different configuration as you can see [here](https://github.com/mishoo/UglifyJS2#compressor-options)
Please give us a object of full options. Thinking what options I can pass is a headache.

**Comment by MasterOfZozo** [comment]
ping @terinjokes

**Comment by terinjokes** [comment]
Aside from `preserveComments` all options are passed directly through to UglifyJS. I don't have a list of all the possible options.
