### ISSUE TITLE
Two recent package updates break the js in my project.

### ISSUE THREAD

**Issue by JoelParke** [terinjokes/gulp-uglify#254]
I have a large project with many included packages. Two of the recent updates:

angular-timezone-selector@1.6.0 
jwt-decode@2.0.3 
break the minimized js code. And 'gulp serve' works fine when uglify is not invoked. Using:

 .pipe(plugins.uglify({mangle: false, compress:false}))
doesn't keep the js from being broken.

The breakage is different for the two packages:

1) angular-timezone-selector.js must have a ';' added at the end of the

angular.module('angular-timezone-selector'....)
.factory(...)
.factory(...)
.directive(...)
NOTE: however that this ';' is not needed by js.

2) awt-decode breaks something else... but what exactly is not clear.

I can provide the build file, the minimized js, etc..  if that would be helpful.  Since I am sure that the breakage is dependent on the exact files, etc... 

The bower.json in my case is:
{
  "name": "tracker2",
  "version": "1.0.0",
  "dependencies": {
    "jquery": "~3.1.1",
    "angular": ">=1.5.*",
    "angular-base64": "~2.0.5",
    "angular-bootstrap-colorpicker": "~3.0.25",
    "angular-cookies": ">=1.5.*",
    "angular-dragdrop": "~1.0.13",
    "angular-md5": "~0.1.10",
    "angular-moment": "~1.0.0-beta.6",
    "angular-resource": ">=1.5.*",
    "angular-route": ">=1.5.*",
    "angular-socket-io": "~0.7.0",
    "angular-timezone-select": "~1.1.3",
    "angular-uri": "*",
    "angular-validation-match": "~1.9.0",
    "bootstrap-sass-official": "~3.3.7",
    "bootstrap": "~3.3.7",
    "bootstrap-social": "~5.1.1",
    "chosen": "~1.6.2",
    "eonasdan-bootstrap-datetimepicker": "~4.17.37",
    "es5-shim": "~4.5.8",
    "font-awesome": "^4.6.3",
    "json3": "~3.3.2",
    "jstz": "https://github.com/bower-packages/bower-jstz.git",
    "jwt-decode": "~2.0.3",
    "lodash": "^4.16.4",
    "moment": "~2.17.0",
    "moment-timezone": "~0.5.10",
    "ng-context-menu": "~1.0.1",
    "ng-file-upload": "~12.2.13",
    "ng-stats": "~2.5.4",
    "power-assert": "~1.4.2",
    "sprintf": "~1.0.2",
    "textAngular": "*",
    "angular-timezone-selector": "~1.6.0",
    "angular-strap": "^2.3.10",
    "angular-animate": "^1.5.9",
    "select2": "^4.0.3"
  },
  "devDependencies": {
    "angular-mocks": ">=1.5.*",
    "angular-scenario": ">=1.5.*"
  },
  "resolutions": {
    "angular": ">=1.5.*",
    "lodash": "^4.12.0",
    "moment": "~2.13.0",
    "moment-timezone": "~0.5.4",
    "font-awesome": "^4.6.3"
  }
}

**Comment by terinjokes** [comment]
Please file minification bugs against the UglifyJS project. I don't have any control over the minification.
