### ISSUE TITLE
Arrow Function Syntax not supported

### ISSUE THREAD

**Issue by jhfernan** [terinjokes/gulp-uglify#257]
Trying to minify the following using the latest arrow functions from ECMAScript:

```javascript

$( ".rotate" ).on( 'click', () => {
	$( this ).toggleClass( "rotate-45" );
});

```

and getting the throw error.

Will we be getting support for ECMAScript sometime soon?

**Comment by terinjokes** [comment]
Maybe? See https://github.com/mishoo/UglifyJS2/issues/448.
