### ISSUE TITLE
Not useful error information 

### ISSUE THREAD

**Issue by djake** [terinjokes/gulp-uglify#262]
I am getting "GulpUglifyError: unable to minify JavaScript". Followed by a stacktrace with doesn't point me toward my source. I suspect the root cause is due to ES6 code which I will happily remove, but I cannot find it based on this information, and I've already combed through the obvious culprits. Is there anything I can do to get a source file name, or a snippet of the offending code? I am running 2.0.1.

**Comment by terinjokes** [comment]
Have you read the “Why Use Pump?” documentation as recommended by the [Errors](https://github.com/terinjokes/gulp-uglify#errors) section of the README?

**Comment by djake** [comment]
Perfect. Thank you for the quick response.
