### ISSUE TITLE
Remove custom options

### ISSUE THREAD

**Issue by yairEO** [terinjokes/gulp-uglify#265]
I've wasted time thinking `preserveComments` was an option for `uglify` when all along it was a specific thing added to `gulp-uglify` all because the options are all dumped together without clean headers or separation between what is what :/  

The time I've wasted will not return but at least I might save somebody's else time by opening a ticket about this.

--------
Was trying to use the same options for `gulp-uglify` and for `rollup-plugin-uglify` and couldn't understand why Gulp crashes all the time. I dug and dug until I've found that `rollup-plugin-uglify` doesn't know what `preserveComments` means.

**Comment by terinjokes** [comment]
In version 3.0.0, I'll be removing custom options in favor of one defined upstream with any remaining options specifically grouped in a key for `gulp-uglify`.

**Comment by terinjokes** [comment]
@yairEO I've removed all the custom options in my "three" branch, which will be the next major version.

I'm closing this issue since this work is now done.
