### ISSUE TITLE
pipe finished { GulpUglifyError: unable to minify JavaScript } - Stream.js Unhandled Stream Error

### ISSUE THREAD

**Issue by Nitin-Prabhakar** [terinjokes/gulp-uglify#276]
While Minifying, 

Uglify encountered a closure that has parameter values initialized within the function definition.

Like So:

```
var myFunc = (function(){
       return function ( initialize = true, id = "space" ) {
               do  blah blah blah
       };
})
```
Using [PumP](https://www.npmjs.com/package/pump),
I got this screenshot of the detailed traceback to the origin of the error
![screenshot from 2017-03-14 14-46-33](https://cloud.githubusercontent.com/assets/15086525/23893665/63831ed0-08c5-11e7-8976-9d88f07fc7f0.png)
which traces back to the line , 

`return function ( initialize = true, id = "space" ) {`

in my js file.

Why should this be an issue? I remove the parameter initializations, and uglify works fine.

**Comment by terinjokes** [comment]
UglifyJS doesn't yet support ES6.

**Comment by Nitin-Prabhakar** [comment]
Ah! Will you accommodate ES6 syntax any time soon? Thanks for the awesome plugin otherwise!

**Comment by parkerproject** [comment]
transform with babel before minifying
