### ISSUE TITLE
plz give more demos in REMDME

### ISSUE THREAD

**Issue by Jam1zhu** [terinjokes/gulp-uglify#277]
In a gulp project
```
uglify(
    mangle:true     // does't work
)
```
Then I googled for about half an hour to find a solution
```
uglify(
   mangle:{
      toplevel: true    // works
   }
)
```
Hope to add  some detailed demos to the note, so novices would accept this plugin easily.Thanks.

**Comment by terinjokes** [comment]
@Jam1zhu I'd rather have the API for UglifyJS be documented upstream so that I can just link to them (and we don't have to duplicate work). Would you mind starting to contribute them there?

**Comment by terinjokes** [comment]
It's looking like the upcoming v3 release of UglifyJS will have better documentation.

**Comment by terinjokes** [comment]
On the "three" branch (which contains the next major version) I now link to the UglifyJS3 documentation, which is now much better.

I'd still love a "recipes" folder with examples, if you have time to contribute something, but in the meantime I'm going to close this issue.
