### ISSUE TITLE
Should first determine whether the JS file, or do not plug

### ISSUE THREAD

**Issue by RodeyManager** [terinjokes/gulp-uglify#279]
`if(!/\.(js|es6)$/i.test(file.path)){
        return callback(null, file);
 }`

**Comment by terinjokes** [comment]
You can easily so this outside or gulp-uglify.

**Comment by RodeyManager** [comment]
Since it is JavaScript compression, should only focus on JS code, filter out other

**Comment by terinjokes** [comment]
Filtering out files is not the goal of this project, and I don't want to make any assumptions about what file extensions user might use (especially if they're compiling from other languages). You can use `gulp-if` or similar within your pipeline to get the desired functionality.
