### ISSUE TITLE
only change the line length

### ISSUE THREAD

**Issue by croucha** [terinjokes/gulp-uglify#282]
@terinjokes, is it possible to setup the uglify options for this to only control max line length? No, condensing, minification, etc.  Only the max line length.  I tried the options below but it still mush's everything together. I think I need someway to tell it not to remove whitespace or carriage returns?

uglifyJsOptions: {
            mangle: false,
            compress: false
        },

**Comment by terinjokes** [comment]
I think you can get closer to what you want with:

```javascript
var uglifyJSOptions = {
    mangle: false,
    compress: false,
    output: {
      beautify: true
    }
};
```

**Comment by croucha** [comment]
You rock homey! This is what I did and it worked great:

uglifyJsOptionsLineLengthCut: {
            mangle: false,
            compress: false,
            output: {
                beautify: true,
                max_line_len: 7000 // Clear case max line length is 8000
            }
        }
