### ISSUE TITLE
GulpUglifyError: unable to minify JavaScript `fromString` is not a supported option

### ISSUE THREAD

**Issue by pepone** [terinjokes/gulp-uglify#285]
Hi,

I trying to use gulp-uglify with uglify from harmony branch and keep getting this error

    [11:55:09] GulpUglifyError: unable to minify JavaScript
    Caused by: DefaultsError: `fromString` is not a supported option
    File: /Users/jose/Documents/ZeroC/3.7/ice/js/lib/Ice.js

My gulpfile is like this:

    var pump        = require('pump'),
        uglify      = require('uglify-js'),
        minifier    = require('gulp-uglify/minifier');

    gulp.task(minLibTask(lib), [libTask(lib)],
                function(cb){
                    pump([
                        gulp.src(libFile(lib)),
                        minifier({compress:false}, uglify),
                        extreplace(".min.js"),
                        gulp.dest("lib")], cb);
                });

I using  gulp-uglify `2.1.2` and uglify-js `github:mishoo/UglifyJS2#harmony`, any ideas how to get this to work?

Regards,
José

**Comment by terinjokes** [comment]
@pepone: the Harmony branch is now based on the un-stable 3.0.0 version, which changes the API. You'll need to pick an older version, or wait until after I support the 3.x branch.

**Comment by pepone** [comment]
@terinjokes  Thanks for the info I switch to github:mishoo/UglifyJS2#harmony-v2.8.22 and things are back to work.
