### ISSUE TITLE
UglifyJS 3 support

### ISSUE THREAD

**Issue by meriturva** [terinjokes/gulp-uglify#286]
Will you support UglifyJS 3 version?
So thanks.
Diego

**Comment by meriturva** [comment]
Ok i have seen milestone: https://github.com/terinjokes/gulp-uglify/milestone/1

any eta?

**Comment by terinjokes** [comment]
@meriturva No, there's no ETA. I'm hesitant to immediately upgrade, since these early releases tend to have bugs. I'll probably have a beta up sometime this weekend.

**Comment by meriturva** [comment]
You are right @terinjokes !
