### ISSUE TITLE
Does not work with uglify-es?

### ISSUE THREAD

**Issue by davistan** [terinjokes/gulp-uglify#287]
Hi, I've just tried to process a ES6 file using uglify-es.

The same file running on `uglifyjs` CLI works but using the minifier will produce error.

Using pump, produces error below:
`Caused by: TypeError: Cannot read property 'replace' of undefined`

Hope this can be fixed easily.

Thanks in advance.

**Comment by davistan** [comment]
Just saw this - perhaps this is caused by this: https://github.com/mishoo/UglifyJS2/issues/1907

**Comment by terinjokes** [comment]
@davistan Probably. You'll be able to use it after we release a beta supporting v3 of UglifyJS.

**Comment by davistan** [comment]
Noted. Thanks!

**Comment by terinjokes** [comment]
@davistan Be aware I'm likely to include a breaking change of this feature in the next major release, see #291.

**Comment by KennethanCeyer** [comment]
I hope you include these fixes ASAP.

Thank you.

**Comment by KennethanCeyer** [comment]
I faced same problem and solved this problem.

I can solve this problem to downgrade `uglify-js` to `v2.8.10`.

```bash
# Delete uglify-js@3.0.x
$ npm uninstall uglify-js --save-dev

# Re-install that plugin v2.8.10 version
$ npm install uglify-js@2.8.10 --save-dev
```

**Comment by terinjokes** [comment]
@kennethanceyer if you're not using a specific version of UglifyJS, you don't have to install it: by default you'll get the latest version of UglifyJS2 and you can use the normal import.

**Comment by KennethanCeyer** [comment]
@terinjokes 

I understand and now checked `gulp-uglify` has dependency `uglify-js@2.8.10`

I had mistake, i installed `uglify-js` directly.

I hope this comment will be helped who have faced same error.

**Comment by diasdavid** [comment]
@KennethanCeyer for me that wasn't the full solution as it would disable me from using ES6 features.

I had to install uglify-js on this specific commit: `"uglify-js": "github:mishoo/UglifyJS2#7906033e82d66f2735f8626e98f0f7352d9b3d25",` - ref https://github.com/dignifiedquire/aegir/pull/130/files

Hope this helps for ES6 users out there :)

**Comment by terinjokes** [comment]
@diasdavid If you install from my "three" branch, you can use `uglify-es`, but as I noted in a comment above, the API will likely change tonight (before I do a release of `gulp-uglify@3`)

**Comment by diasdavid** [comment]
thanks @terinjokes. I'll keep posted :)

**Comment by gluttonman** [comment]
@terinjokes  Today, i use uglify-js@3.0 that  has a feature {ie8:true}.But, gulp-uglify unsupport this property.because  gulp-uglify  property {fromString:true} that uglify-js@3.0 unsupport!

**Comment by terinjokes** [comment]
@gluttonman you can install an alpha version of gulp-uglify@3 from the "three" git branch.

**Comment by gluttonman** [comment]
@terinjokes thank you!
