### ISSUE TITLE
Extra Backslash Added in Uglified Output of Regex

### ISSUE THREAD

**Issue by ScottHaney** [terinjokes/gulp-uglify#289]
When running gulp-uglify on a certain regex inside of a docker container I am seeing an extra backslash being added to the uglified regex. I created a minimal example and posted the docker file as well as its supporting files [here](https://github.com/AlmondBranch/docker-images/tree/master/problem-images/uglifier-regex-issue).

I did try out the original regex and the outputted one with the extra backslash and they seem to be behaving identically as far as I can tell. It is causing a problem for me as other builds are not outputting the backslash and a hash of the uglified output is being used to verify the integrity of the file. The extra backslash that is being outputted on my build is causing the hash not to match.

Also it would be nice if the outputted regex wasn't changed. I should mention though that the regex outputted by the uglifier is how I would have expected the regex to look in the first place. The regex that I am using is from a well used piece of code so it is working (or at least seems to users like it is).

**Comment by terinjokes** [comment]
@ScottHaney This is something UglifyJS does, not gulp-uglify. Please file an issue with that project.

**Comment by ScottHaney** [comment]
Thank you for your prompt response! I [created a new issue for UglifyJS](https://github.com/mishoo/UglifyJS2/issues/1929) and got a fix for the issue.
