### ISSUE TITLE
 Unexpected token: operator (<)',

### ISSUE THREAD

**Issue by tejareddy457** [terinjokes/gulp-uglify#290]
Hi,

Thank you in advance
i am running out of problem as described below

i have index.html which has all script file included and when running gulp command it gives me Unexpected token: operator 

Here versions 
node : v6.10.03
npm: 3.10.10

Not able to debug which js file caused the problem

return gulp.src(sourcePath)
				.pipe(plumber())
				.pipe(useref()) // Does not seams to work with gulp-sourcemaps@1.11.1
				.pipe(gulpIf('*.js',ngAnnotate({
					// true helps add where @ngInject is not used. It infers.
					// Doesn't work with resolve, so we must be explicit there
					add: true
				})))
// The below line is giving error
				.pipe(gulpIf('*.js' && elixir.config.production,uglify({mangle: true}).on('error', function(err){
  console.log(err);
})))
				.pipe(gulp.dest(elixir.config.publicPath));
=======
Stacktrace
=========
[20:36:06] Starting 'useref2'...
{ Error
    at new JS_Parse_Error (eval at <anonymous> (D:\Development\Volvo\eBiz\main\w
ebroot\m\node_modules\gulp-uglify\node_modules\uglify-js\tools\node.js:1:0), <an
onymous>:1534:18)
    at js_error (eval at <anonymous> (D:\Development\Volvo\eBiz\main\webroot\m\n
ode_modules\gulp-uglify\node_modules\uglify-js\tools\node.js:1:0), <anonymous>:1
542:11)
    at croak (eval at <anonymous> (D:\Development\Volvo\eBiz\main\webroot\m\node
_modules\gulp-uglify\node_modules\uglify-js\tools\node.js:1:0), <anonymous>:2089
:9)
    at token_error (eval at <anonymous> (D:\Development\Volvo\eBiz\main\webroot\
m\node_modules\gulp-uglify\node_modules\uglify-js\tools\node.js:1:0), <anonymous
>:2097:9)
    at unexpected (eval at <anonymous> (D:\Development\Volvo\eBiz\main\webroot\m
\node_modules\gulp-uglify\node_modules\uglify-js\tools\node.js:1:0), <anonymous>
:2103:9)
    at expr_atom (eval at <anonymous> (D:\Development\Volvo\eBiz\main\webroot\m\
node_modules\gulp-uglify\node_modules\uglify-js\tools\node.js:1:0), <anonymous>:
2630:9)
    at maybe_unary (eval at <anonymous> (D:\Development\Volvo\eBiz\main\webroot\
m\node_modules\gulp-uglify\node_modules\uglify-js\tools\node.js:1:0), <anonymous
>:2792:19)
    at expr_ops (eval at <anonymous> (D:\Development\Volvo\eBiz\main\webroot\m\n
ode_modules\gulp-uglify\node_modules\uglify-js\tools\node.js:1:0), <anonymous>:2
827:24)
    at maybe_conditional (eval at <anonymous> (D:\Development\Volvo\eBiz\main\we
broot\m\node_modules\gulp-uglify\node_modules\uglify-js\tools\node.js:1:0), <ano
nymous>:2832:20)
    at maybe_assign (eval at <anonymous> (D:\Development\Volvo\eBiz\main\webroot
\m\node_modules\gulp-uglify\node_modules\uglify-js\tools\node.js:1:0), <anonymou
s>:2856:20)
  message: 'D:\\Development\\Volvo\\eBiz\\main\\webroot\\m\\src\\index.html: Syn
taxError: Unexpected token: operator (<)',
  fileName: 'D:\\Development\\Volvo\\eBiz\\main\\webroot\\m\\src\\index.html',
  lineNumber: 1,
  stack: 'Error\n    at new JS_Parse_Error (eval at <anonymous> (D:\\Development
\\Volvo\\eBiz\\main\\webroot\\m\\node_modules\\gulp-uglify\\node_modules\\uglify
-js\\tools\\node.js:1:0), <anonymous>:1534:18)\n    at js_error (eval at <anonym
ous> (D:\\Development\\Volvo\\eBiz\\main\\webroot\\m\\node_modules\\gulp-uglify\
\node_modules\\uglify-js\\tools\\node.js:1:0), <anonymous>:1542:11)\n    at croa
k (eval at <anonymous> (D:\\Development\\Volvo\\eBiz\\main\\webroot\\m\\node_mod
ules\\gulp-uglify\\node_modules\\uglify-js\\tools\\node.js:1:0), <anonymous>:208
9:9)\n    at token_error (eval at <anonymous> (D:\\Development\\Volvo\\eBiz\\mai
n\\webroot\\m\\node_modules\\gulp-uglify\\node_modules\\uglify-js\\tools\\node.j
s:1:0), <anonymous>:2097:9)\n    at unexpected (eval at <anonymous> (D:\\Develop
ment\\Volvo\\eBiz\\main\\webroot\\m\\node_modules\\gulp-uglify\\node_modules\\ug
lify-js\\tools\\node.js:1:0), <anonymous>:2103:9)\n    at expr_atom (eval at <an
onymous> (D:\\Development\\Volvo\\eBiz\\main\\webroot\\m\\node_modules\\gulp-ugl
ify\\node_modules\\uglify-js\\tools\\node.js:1:0), <anonymous>:2630:9)\n    at m
aybe_unary (eval at <anonymous> (D:\\Development\\Volvo\\eBiz\\main\\webroot\\m\
\node_modules\\gulp-uglify\\node_modules\\uglify-js\\tools\\node.js:1:0), <anony

**Comment by terinjokes** [comment]
Please read the "Why Use Pump?" article linked in the README.
