### ISSUE TITLE
Consider new API for swapping UglifyJS versions

### ISSUE THREAD

**Issue by terinjokes** [terinjokes/gulp-uglify#291]

**Comment by terinjokes** [comment]
My ideal API for this would look like this:

```javascript
var gulp = require('gulp');
var uglify = require('gulp-uglify/minifer')(require('uglify-es'));
var pump = require('pump');

gulp.task('compress', function (cb) {
  pump([
        gulp.src('lib/*.js'),
        uglify({warnings: true}),
        gulp.dest('dist')
    ],
    cb
  );
});
```

**Comment by davistan** [comment]
IMHO, we can use the same API as current like `minifier(options, uglifyes)`.
You may want to consider supporting an option for { "uglifyApiVer": 3 } to maintain consistent API.

That's my suggestion.

**Comment by pioug** [comment]
I am not following closely 🙈 the development of your plugin or UglifyJS itself but can you (@terinjokes) explain quickly why it can be useful to swap between UglifyJS version? I always thought that latest UglifyJS (`uglify-es`) is the best and everyone would eventually update.

**Comment by terinjokes** [comment]
@pioug because many people want to use forks, or they want to use `uglify-es` now. If you don't find it useful, nothing is making you do so.

@davistan I don't like the current API, other people I've talked to don't like the current API. I really don't plan on keeping it.

**Comment by davistan** [comment]
That’s fine. Just a suggestion, whichever way works.

Cheers!
