### ISSUE TITLE
Potential ES6 Issues

### ISSUE THREAD

**Issue by mlefleur** [terinjokes/gulp-uglify#292]
I haven't tried everything new in ES6, but I noticed that if a javascript file contains `let` instead of `var`, an error is thrown.

**Comment by mlefleur** [comment]
After reading around, I believe this is a known issue, and a current solution is to use babel

**Comment by terinjokes** [comment]
@mlefleur as noted in the README, you might also try `uglify-js-harmony` (or after upgrading to v3, `uglifyjs-es`)
