### ISSUE TITLE
README could use more examples for options to uglify()

### ISSUE THREAD

**Issue by ORESoftware** [terinjokes/gulp-uglify#299]
Say we have:

```js
 pump([
        gulp.src('lib/*.js'),
        uglify(),
        gulp.dest('dist')
    ],
```

which options can we pass to uglify()?
Are the options verbatim what's documented in the uglifyjs2 project?

Specifically I am looking to strip console.log / console.error statements from my front-end code.

**Comment by ORESoftware** [comment]
It says to drop console, use this:

`drop_console -- default false. Pass true to discard calls to console.* functions. If you wish to drop a specific function call such as console.info and/or retain side effects from function arguments after dropping the function call then use pure_funcs instead.`

My guess is that this will work:

```js
 pump([
        gulp.src('lib/*.js'),
        uglify({dropConsole:true}),
        gulp.dest('dist')
    ],
```

but this is just a guess, and I hate guessing :/

**Comment by ORESoftware** [comment]
but I get this:

```console
[14:24:10] Using gulpfile ~/WebstormProjects/cisco/cdt-now/gulpfile.js
[14:24:10] Starting 'compress'...
[14:24:10] 'compress' errored after 51 ms
[14:24:10] GulpUglifyError: unable to minify JavaScript
Caused by: DefaultsError: `dropConsole` is not a supported option
File: /Users/alexamil/WebstormProjects/cisco/cdt-now/public/app.js
```

:(

**Comment by terinjokes** [comment]
That option is a [compress option](https://github.com/mishoo/UglifyJS2#compress-options), so it needs to be provided in the `compress` section.

```javascript
 pump([
        gulp.src('lib/*.js'),
        uglify({
                compress: {
                        drop_console: true
                }
        }),
        gulp.dest('dist')
    ],
```

PR requests accepted for examples.

**Comment by ORESoftware** [comment]
ok thanks! :)

**Comment by ORESoftware** [comment]
That would be a great addition to the README btw
