### ISSUE TITLE
Converting Numbers to incorrect Hex

### ISSUE THREAD

**Issue by STDGA** [terinjokes/gulp-uglify#303]
Hi, i found out that after uglifying the javascript, the numbers are converted incorrectly. Instead of "1000" in the result i have "1e3" and it is not the correct value.

**Comment by mabar** [comment]
gulp-uglify is only a wrapper for [uglify-js](https://github.com/mishoo/UglifyJS2) so it is not this package issue.
Moreover, 1e3 means 1000. [See here](https://stackoverflow.com/questions/25646062/why-does-js-minification-covert-1000-to-1e3)

**Comment by terinjokes** [comment]
Thanks @mabar for answering this. :+1:
