### ISSUE TITLE
Question: Is there a way to minify file without any renaming and code optimization/transformation?

### ISSUE THREAD

**Issue by ifle** [terinjokes/gulp-uglify#306]
Is there a way to minify file without any renaming and code optimization/transformation?
I need removing the whitespaces only.

**Comment by terinjokes** [comment]
Have you tried passing options to gulp-uglify? I think something similar to the following will get you close:

```javascript
var uglifyJSOptions = {
    mangle: false,
    compress: false
};
```

**Comment by ifle** [comment]
Thanks.
Something strange. When I use uglify without any compiler options I have incorrect JS.
Following code 
```js
function Foo() 
{    
	return new Array();    
}
```
transformed to incorrect code
 ```js
function Foo(){return new Array}
```

What is wrong?
gulpfile
````js
gulp.task('js-min', ["cleanup"], function() {           
    return gulp.src([ path.join(jsSourcePath, "*.js"), path.join(jsSourceCustomPath, "*.js") ])     
    .pipe(uglify())        
    .pipe(gulp.dest(jsDestPath));
});
````
