### ISSUE TITLE
Uglify File but don't minify certain strings

### ISSUE THREAD

**Issue by matthew1534** [terinjokes/gulp-uglify#307]
Is it possible using UglifyJS2 with gulp to effectivly ignore certain strings such as: 

{% if VARIABLE == VARIABLE %}
{% else %}
{% elseif VARIABLE > VARIABLE %}
{% endif %}

Essentially, we are using liquid in our js as we are on the Shopify eccomerce platform. But we need the liquid to remain exactly how it is so that Shopify can process the liquid.

Many thanks for any help you can provide!

**Comment by terinjokes** [comment]
@matthew1534 I'm actually not sure. Perhaps ask about it on StackOverflow with the "uglifyjs" tag?
