### ISSUE TITLE
Error on strings wrapped with ``

### ISSUE THREAD

**Issue by BehnamAbdy** [terinjokes/gulp-uglify#312]
for some reasons inside angular we wrap long string inside `` instead of '' or "", 
example: var temp = `some value for my string`;
then i noticed that gulp-uglify crashes when gets that line

**Comment by terinjokes** [comment]
@BehnamAbdy You need to use the in-development fork of uglify-js, as documented in the README. The current stable release doesn't support ES6 fully yet.
