### ISSUE TITLE
Enclose Option to Uglify

### ISSUE THREAD

**Issue by arb** [terinjokes/gulp-uglify#32]
Is there a way to pass the enclose option into UglifyJS2? I would like my outputted file to be wrapped in a function to prevent polluting the global namespace.

If this is something an additional plugin solves, what plugin would that be? I thought maybe "concat" and just do the wrapping myself but that seems a little hacky.

**Comment by indolering** [comment]
It would be helpful if this limitation (and workarounds like gulp-wrap) was documented in the readme.

**Comment by terinjokes** [comment]
I agree, expect more awesome docs shortly.
