### ISSUE TITLE
Compressed symbol ` error

### ISSUE THREAD

**Issue by Mozhate** [terinjokes/gulp-uglify#321]
Compressed symbol ` error

**Comment by Mozhate** [comment]
Such as:
var gu=`aaa${lp}bbb`;

**Comment by Mozhate** [comment]
Such as:
var gu = `aaa${lp}bbb`;

**Comment by terinjokes** [comment]
You need to use a version of UglifyJS that supports harmony features. There's an example in the [README](https://github.com/terinjokes/gulp-uglify#using-a-different-uglifyjs)
