### ISSUE TITLE
JS file having const keyword fails during uglification

### ISSUE THREAD

**Issue by parthsw** [terinjokes/gulp-uglify#332]
I was trying to uglify JS file using this module but it is failing due to the use of ES6 const keyword. Just wondering whether this module is going to provide the support for it?

![image](https://user-images.githubusercontent.com/30234487/39418223-cea1801c-4c76-11e8-8852-aad14546fa81.png)

**Comment by terinjokes** [comment]
This module will provide support for it when UglifyJS does.
