### ISSUE TITLE
Uglify Fails When Using let In Function Definitions

### ISSUE THREAD

**Issue by ryuhhnn** [terinjokes/gulp-uglify#338]
I've run across this a few times, but when using `let` declarations inside function definitions, `uglify()` will fail with the error: `SyntaxError: Unexpected token: name (<VARIABLE NAME>)`. The project we are using is tied down to gulp-uglify v1.5.4, but I was able to recreate this using the latest version as well. Pattern that I've followed to produce this issue is as follows:

```javascript
function doSomething() {
    let foo = document.querySelectorAll('.foo')

    foo.forEach(function(bar) {
        console.log(bar)
    })
}
```

**Comment by Alecto** [comment]
the same.
no support?

**Comment by terinjokes** [comment]
You have to follow the instructions from the README for harmony features.

**Comment by ryuhhnn** [comment]
Thank you for the reply, but I'm still not sure that this issue is resolved as there is nothing in the README describing this issue or any harmony features. I've switched to webpack so I no longer need anything here so I'll close this issue.

**Comment by terinjokes** [comment]
> # Using a Different UglifyJS
>
> By default, gulp-uglify uses the version of UglifyJS installed as a dependency. It's possible to configure the use of a different version using the "composer" entry point.
>
> ```js
> var uglifyjs = require('uglify-js'); // can be a git checkout
>                                      // or another module (such as `uglify-es` for ES6 support)
> var composer = require('gulp-uglify/composer');
> var pump = require('pump');
>
> var minify = composer(uglifyjs, console);
>
> gulp.task('compress', function (cb) {
>   // the same options as described above
>  var options = {};
>
>   pump([
>       gulp.src('lib/*.js'),
>       minify(options),
>       gulp.dest('dist')
>     ],
>     cb
>   );
> });
> ```
