### ISSUE TITLE
GulpUglifyError: unable to minify JavaScript Caused by: SyntaxError when using let or const

### ISSUE THREAD

**Issue by Alecto** [terinjokes/gulp-uglify#344]
I am using the latest version 3.0.1 and gulp 4.0.
Why is the minimization of js files not performed if there is a let or const in the code?

code in js that cannot handle the plugin.

```
'use strict';

let slideItems    = document.querySelectorAll('.slides__item'),
    indContainer  = document.querySelector('.indicators'),
    indItems      = document.querySelectorAll('.indicators__item'),
    currentSlide  = 0;

const LEFT_ARROW  = 37,
      RIGHT_ARROW = 39,
      SPACE       = 32,
      FA_PAUSE    = '<i class="fas fa-pause"></i>',
      FA_PLAY     = '<i class="fas fa-play"></i>';

```
gulp 4 function for task (it works well with vars)
```
function minjs () {
  return src([path.js.files, '!' + path.js.filesMin])
    .pipe(uglify({
      toplevel: true,
    }))
    .pipe(rename({ suffix: '.min' }))
    .pipe(dest(path.js.folder)
      .on('end', () => { if(true) console.log('   ---------------   completed UGLIFY (.min.js)'); }));
}
```

**Comment by terinjokes** [comment]
You should be able to use this module by following the instructions in the README and using the maintained fork of UglifyJS: [Terser](https://github.com/terser-js/terser).

uglify-es is no longer maintained and breaks scripts.

**Comment by DesWurstes** [comment]
Is there a plan to migrate this package to terser?

**Comment by terinjokes** [comment]
You can do so right now, following the instructions in the readme. PRs
accepted to update the example to specifically reference it.
