### ISSUE TITLE
Found a stupid behavior: unnecessary compilation and cause some error

### ISSUE THREAD

**Issue by yesongling** [terinjokes/gulp-uglify#345]
source
![image](https://user-images.githubusercontent.com/28178382/48326269-5cf52f80-e673-11e8-848a-3c62dada5b5b.png)

compilation
![image](https://user-images.githubusercontent.com/28178382/48326285-6e3e3c00-e673-11e8-9ade-9330ab4c2416.png)

you know arguments object is not a real Javascript Array type, so use arguments[0] cannot get the first element of arguments object.  but actually the gulp-uglify compress it from arguments['0'] to arguments[0]. that is the problem.

i can solve this problem by passing parameters instead, but i think it is still a compress issue

**Comment by terinjokes** [comment]
gulp-uglify does no compression itself, instead relying on UglifyJS
directly.

You should attempt to reproduce with their CLI to, and report a bug to them.

**Comment by yesongling** [comment]
OK, thanks
