### ISSUE TITLE
gulp-uglify changes behavior of javascript

### ISSUE THREAD

**Issue by Stadly** [terinjokes/gulp-uglify#346]
See this [CodePen](https://codepen.io/Stadly/pen/MzVzzB). It shows how [Parsley.js](https://github.com/guillaumepotier/Parsley.js) v2.8.1 changes behavior when uglified by gulp-uglify v3.0.1.

In particular, `<input type="date" min="2000-01-02" max="2179-06-06" value="2018-11-23">` is invalidated by the uglified version of Parsley.js, but not when Parsley.js is not uglified.

**Comment by terinjokes** [comment]
I just work on the plugin for Gulp. If you have an issue with how UglifyJS
minifies, you need to report it to them.

**Comment by Stadly** [comment]
Submitted directly to UglifyJs. https://github.com/mishoo/UglifyJS2/issues/3300
