### ISSUE TITLE
Npm link is broken

### ISSUE THREAD

**Issue by s0xzwasd** [terinjokes/gulp-uglify#347]
[NPM](https://www.npmjs.com/package/gulp-uglify) link — «For more information, see [Why Use Pump?](https://github.com/terinjokes/gulp-uglify/blob/HEAD/docs/why-use-pump/README.md#why-use-pump).» is broken.

**Comment by terinjokes** [comment]
I haven't released a new version of gulp-uglify since renaming the document [Why Use Pipeline?](https://github.com/terinjokes/gulp-uglify/blob/master/docs/why-use-pipeline/README.md#why-use-pipeline)
