### ISSUE TITLE
TypeError: aStr.charAt is not a function

### ISSUE THREAD

**Issue by afeiship** [terinjokes/gulp-uglify#361]
I found the uglify@latest has bug.
You have to locked uglify-js@3.7.2

**Comment by alexlamsl** [comment]
Reported in https://github.com/mishoo/UglifyJS2/issues/3780 &minus; will be fixed in `uglify-js@3.9.1` once the tests pass.

**Comment by afeiship** [comment]
@alexlamsl 
Great! thanks.

**Comment by alexlamsl** [comment]
`uglify-js@3.9.1` has been released &minus; in the future please file related issues like this one at https://github.com/mishoo/UglifyJS2/issues where I will be able to respond faster.
