### ISSUE TITLE
Using a domain property in MakeCallback is deprecated. Use the async_context variant of MakeCallback or the AsyncResource class instead.

### ISSUE THREAD

**Issue by ghost** [terinjokes/gulp-uglify#363]
I got an warning error when gulify js file

`(node:40475) [DEP0097] DeprecationWarning: Using a domain property in MakeCallback is deprecated. Use the async_context variant of MakeCallback or the AsyncResource class instead.`

Here is my code

```
gulp.task('minify-js', async function() {
    await gulp.src('./source/js/SimpleCore.js')
        .pipe(babel())
        .pipe(uglify())
        .pipe(rename({ extname: '.min.js' }))
        .pipe(gulp.dest('./source/js'));
});
```

When remove **pipe(uglify())** everything is fine. But if added nothing will be generated...

Node version is 12.16.0....

![image](https://user-images.githubusercontent.com/68777995/88479651-50b62080-cf83-11ea-8286-918e9273c0eb.png)

**Comment by tangkunyin** [comment]
+ 1

**Comment by terinjokes** [comment]
This is a warning, not an error. It also doesn't come as a result of this project.
