### ISSUE TITLE
No output if uglify method is called

### ISSUE THREAD

**Issue by sunilw** [terinjokes/gulp-uglify#367]
Calling this task results in nothing being written to the destination directory

```
gulp.task('compress', function () {
  return pipeline(
        gulp.src('./src/js/**.js'),
      uglify(),
        gulp.dest('./out')
  );
});
```

However, if the method 'uglify' is commented out, then files are written to the destination directory.

**Comment by terinjokes** [comment]
There's not enough details to troubleshoot this.
