### ISSUE TITLE
Unable to compress ``

### ISSUE THREAD

**Issue by Mr-Lixiaoqaing** [terinjokes/gulp-uglify#369]
![图片](https://user-images.githubusercontent.com/52234930/150096545-df669e7e-77d2-44b3-8b39-9270dca31249.png)

**Comment by terinjokes** [comment]
UglifyJS doesn't support JSX or harmony. You must use an alternative implementation as explained in the readme, or compile code to ES5.

**Comment by Mr-Lixiaoqaing** [comment]
Thank you for your answer
