### ISSUE TITLE
gulp-uglify does not recognise the const keyword 

### ISSUE THREAD

**Issue by DanielOberlechner** [terinjokes/gulp-uglify#370]
Hi, I use in my Javascript the const keyword and when I try to uglify the code I get a error, that gulp-uglify does not recognise the const keyword. Would it be possible to upgrade the library so that newer js syntax gets no error when using this plugin?

Kind regards,
Daniel Oberlechner

**Comment by terinjokes** [comment]
Daniel,

The UglifyJS project is responsible for compressing, this project is just an adapter for Gulp. The readme explains how to override the version of UglifyJS in favor of forks that support harmony features.

**Comment by DanielOberlechner** [comment]
@terinjokes 
Ah okay, sry my mistake. Could you explain a bit further what exactly I would have to do when I would like to use harmony features.
I'm not as good in programming as I would like to be therefore I'm asking. It would be awesome if you could help me a bit further ... :)

Kind regards,
Daniel Oberlechner
