### ISSUE TITLE
gulp-uglify messing with code order

### ISSUE THREAD

**Issue by isaacalves** [terinjokes/gulp-uglify#55]
I have a stream of javascript files that include jQuery, another vendor library and some "in-house" javascript.

When I use uglify() on that stream, the other vendor library jumps on top of jQuery. 

Why and how that happens, and how to fix it?

```
gulp.task('scripts', function () {

    var vendorFiles = gulp.src(mainBowerFiles())
        .pipe(gulpFilter('*.js'))
        .pipe(order([
            "**/jquery.js",
            "*.js"
        ]))
        .pipe(concat('vendor.js'))
        .pipe(debug({verbose:true}));

    var appFiles = gulp.src('app/js/*.js')
        // .pipe(jshint())
        // .pipe(jshint.reporter('default'))
        .pipe(concat('app.js'));

    return es.concat(vendorFiles, appFiles)
        .pipe(order([
            "vendor.js",
            "app.js"
        ]))
        .pipe(concat('app.js'))
        .pipe(uglify())
        .pipe(gulp.dest('./dist/js'));
});
```

**Comment by ConAntonakos** [comment]
Experienced this as well. @jonathandelgado's temporary fix worked for me.

**Comment by terinjokes** [comment]
Mind testing if the to-be 1.3.0 branch resolves this?

```
npm install git+https://github.com/terinjokes/gulp-uglify.git#uglifyjs-the-hard-way
```

**Comment by ronaldlokers** [comment]
@terinjokes I just did a test with your new code and the problem still exists for me. Please let me know if I can do some more tests.

**Comment by scande3** [comment]
@ronaldlokers - does the following syntax fix your issue:

    .pipe(uglify({compress: {hoist_funs: false, hoist_vars: false}})

(This seems like this solves the issue for me as these are settings from http://lisperator.net/uglifyjs/compress that this library uses)

**Comment by terinjokes** [comment]
@scande3 ah, neither of these libraries wrap themselves in an IIFE? I suppose that could cause the issue seen here. I'll accept a pull request to add some documentation.

**Comment by crocofdev** [comment]
I don't know if this is still a valid issue, however I noticed similar behaviour when combining gulp-uglify with gulp-useref.

If I ran just gulp-useref then the order in the output file was the same as the order the scripts were declared. If I piped the output through uglify the order ended up being changed.

I found a similar issue being raised with Grunt uglify too and a solution posted in there also helped me. So basically the following config solved the issue:

```
.pipe(uglify({
    compress: {
        drop_console: true,
        hoist_funs: false
    }
})

**Comment by alvarotrigo** [comment]
Any solution for this?

**Comment by terinjokes** [comment]
@alvarotrigo I never received a code sample that showed the problem, but I believe this is an issue with the UglifyJS library this problem uses.

**Comment by alvarotrigo** [comment]
@terinjokes solved thanks to [this answer](http://stackoverflow.com/a/39511772/1081396).

**Comment by terinjokes** [comment]
@alvarotrigo The `hoist_funs` feature really shouldn't be breaking things: functions are hoisted to the top of the scope by the JavaScript engine during execution anyways. You should definitely file a bug with UglifyJS2.

**Comment by alvarotrigo** [comment]
@terinjokes I see. Make sense. Fair enough!

**Comment by terinjokes** [comment]
With no disrespect to anyone who's commented on this thread, this thread isn't tracking a specific issue. As it stands right now, there's nothing for me to do next here.

In preparing for the next major release, I'm going to go ahead and close out this ticket. At work we'd call this an "unsolved mystery". 👻 

You're more than welcome to open new tickets with specifics and reproduction steps.

Thanks!
