### ISSUE TITLE
Uglify not working with gulp-sourcemaps

### ISSUE THREAD

**Issue by robianmcd** [terinjokes/gulp-uglify#56]
When I try and uglify my code without concatenating it and then generate source maps I get an error message like:

```
gulp-sourcemap-write: source file not found:C:\Rob\Dropbox\Repos\gulpTest\?
```

my gulp task looks like this

```JavaScript
gulp.task('js', function () {
    return gulp.src('app.js')
        .pipe(sourcemaps.init())
        .pipe(uglify())
        .pipe(sourcemaps.write())
        .pipe(gulp.dest('build'));
});
```

I'm using the following versions of npm modules

```JSON
  "dependencies": {
    "gulp": "3.8.8",
    "gulp-uglify": "1.0.1",
    "gulp-sourcemaps": "1.1.5"
  }
```

There is a zipped up version of the project here https://dl.dropboxusercontent.com/u/20066539/Forum%20Links/Other/gulpTest.zip

This issue is related to https://github.com/floridoo/gulp-sourcemaps/issues/34

**Comment by jmm** [comment]
@terinjokes You ended up accepting #74 to fix this even though I proposed the same solution here almost 2 weeks earlier and you never even commented on it. Is this a fluke and I should continue to expect that if I post a proposed solution in an issue comment that it'll be considered before a later pull request by someone else is accepted and the issue is closed, or do I need to open a pull request in this situation in the future to have my proposal considered?

**Comment by terinjokes** [comment]
@jmm I work on this in batches, and didn't see your earlier comment, sorry for missing it. In general, pull requests have more visibility on GitHub, and as you can see in this thread, @floridoo and I had previously worked on trying to resolve this.

**Comment by jmm** [comment]
> @floridoo and I had previously worked on trying to resolve this.

Yes, I thought that possible solutions were being discussed in this issue, by you and @floridoo and a number of other people. Reviewing the thread I do see that the idea was already discussed in these comments:

@terinjokes
> UglifyJS does not preserve the "sources" array in the source maps it generates. Previous versions of this plugin attempted to correct this, but this introduced several other bugs when UglifyJS re-ordered the sources.

@floridoo
> @terinjokes vinyl-sourcemaps-apply needs a valid sources property in order to work correctly. You can fix this by setting `sources` to ~~`file.relative`~~`file.relative.split(path.sep).join('/')` (= the input file to uglify) on the source map generated by uglify before passing it to vinyl-sourcemaps-apply.

Sorry I missed that. Honestly by the time I'd read through the issue and gone through debugging the problem myself I'd lost track of those comments. It was also about 3 months between those comments (and your last comment about that: "Ok, I'll give this a shot.") and mine, so I think I missed the connection that the "solution" I "discovered" had been on the shelf for 3 months while a bunch of people continued to pipe up asking for / investigating for a solution. 

In the future in this situation I'll create a pull request. Admittedly in this case it still wouldn't have been an original idea.

**Comment by Dr-Steve** [comment]
So is this fixed now in the latest version?  I just tried using the latest version of uglify with source-map and am getting nothing.

**Comment by maxhorizon** [comment]
Same issue here:

gulp.task('js', function () {
    gulp.src(['ng/module.js', 'ng/**/*.js'])
        .pipe(concat('app.js'))
        .pipe(ngAnnotate())
        .pipe(uglify())
        .pipe(sourcemaps.write())
        .pipe(gulp.dest('assets'));
});

I am using the following versions and sourcemaps does not do anything:

"gulp": "^3.8.11",
    "gulp-concat": "^2.5.2",
    "gulp-ng-annotate": "^0.5.2",
    "gulp-sourcemaps": "^1.5.1",
    "gulp-uglify": "^1.1.0",

Regards,
Salim

**Comment by petrsimon** [comment]
This order of pipes works for me

```js
gulp.src(source_paths.scripts)
        .pipe(sourcemaps.init())
        .pipe(ngAnnotate())
        .pipe(uglify({compress: {join_vars: false, sequences: false}}))
        .pipe(concat(dest_paths.scripts))
        .pipe(sourcemaps.write('../sourcemaps'))
        .pipe(gulp.dest('www'))
        .on('end', function () {
            exec('mv sourcemaps/atuhi.js.map sourcemaps/atuhi-' + VERSION + '.js.map');
        })
```

**Comment by cgeo7** [comment]
I'm using:

gulp.src([sources.coffee.core, sources.coffee.all])
	.pipe sourcemaps.init()
	.pipe coffee().on 'error', swallowError
	.pipe concat 'app.min.js'
	.pipe uglify()
	.pipe sourcemaps.write()
	.pipe gulp.dest dist.js

However, I get a sourcemap for app.min.js as well, how can we avoid this?

**Comment by Wenzil** [comment]
@terinjokes I'm getting the same problem as @cgeo7. `uglify` thinks the output of `concat` (app.min.js) is a source and creates an invalid source map for it...

The result is that the browser developer tools show the original coffeescript sources correctly but breakpoints in them don't work. There's a 404 response for `GET app.min.js`.

Without the `uglify` step, everything works.

**Comment by Wenzil** [comment]
So after doing a few more tests, it seems `uglify` doesn't like the way `coffee` passes down its source maps. `concat` doesn't seem to have an effect either way so I've omitted it to isolate the problem.

```javascript
gulp.src('assets/test.coffee')
  .pipe(sourcemaps.init())
  .pipe(coffee()) // produces a correct test.coffee source map
  .pipe(uglify()) // produces an invalid test.js source map
  .pipe(sourcemaps.write())
  .pipe(gulp.dest('./public'));
```

**Comment by efolio** [comment]
After investigating, I found that the issue is the same as in many other
libraries: mozilla's sourcemap library cannot merge two sourcemaps.
The merging function does not do what anyone would expect, thus all plugins
using it don't work.

There is currently no way to implement sourcemap merging. The sourcemaps
format simply isn't compatible with it.
And yes, this sucks.

On Thu, May 14, 2015 at 9:18 AM, Sami Turcotte <notifications@github.com>
wrote:

> So after doing a few more tests, it seems uglify doesn't like the way
> coffee passes down its source maps. concat doesn't seem to have an effect
> either way so I've omitted it to isolate the problem.
>
> gulp.src('assets/test.coffee')
>   .pipe(sourcemaps.init())
>   .pipe(coffee()) // produces a correct test.coffee source map
>   .pipe(uglify()) // produces an invalid test.js source map
>   .pipe(sourcemaps.write())
>   .pipe(gulp.dest('./public'));
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/terinjokes/gulp-uglify/issues/56#issuecomment-101949812>
> .
>



-- 
Etienne Folio
Tel : +33 (0)6 27 58 39 14
L.systems • http://lsystems.fr

**Comment by gkiely** [comment]
Can anyone link to a repo where they have this working?

**Comment by Dr-Steve** [comment]
Never got it working.  Gave up.

**Comment by bf** [comment]
I think I am expecting the same issue with sourcemaps for browserify -> babelify stuff. Anyone got it working?

**Comment by terinjokes** [comment]
@bf It may be significantly easier for you to use `gulp-if` to avoid source maps while in development.

**Comment by bf** [comment]
Thanks, @terinjokes .

Just to spare others the hassle as I have spent a couple of days with this issue, this is my final gulpfile.js with browserify / babel / uglify and sourcemaps:

```
return browserify(inputFile, {
    debug: true,
    extensions: ['.jsx', '.js', '.json'],
    cache: {},
    packageCache: {}
  }).transform(babelify, {
    sourceMaps: true,
    ignore: /(vendor)|(node_modules)/
  }).bundle()
  .pipe(gulpif(!isProductionBuild, exorcist('bundle/js/app.js.map')))
  .pipe(source('app.js'))
  .pipe(gulpif(isProductionBuild, streamify(uglify)))
  .pipe(gulp.dest(config.output.jsDir))
  .pipe(gulpif(!isProductionBuild, livereload()));
```
