### ISSUE TITLE
Name expected?

### ISSUE THREAD

**Issue by blaasvaer** [terinjokes/gulp-uglify#66]
I implemented this:

```
.pipe(uglify().on('error', function(e) { console.log('\x07',e.message); return this.end(); }))
```

to get more describing error messages.
But now I get:
Name expected

My task is as simple as this:

``` javascript
gulp.task('orders_js', function () {
    gulp.src(orders_js) // Javascript files source defined else where as an array (top of file)
//      .pipe(uglify())
        .pipe(uglify().on('error', function(e) { console.log('\x07',e.message); return this.end(); }))
        .pipe(gulp.dest('assets/js/pages'));
});
```

Everything works fine when out commenting the uglify line. As in, the file does output to the right place, so path etc. is all working. But what "Name" is it that uglify "Expects"?

**Comment by NextSeason** [comment]
@terinjokes I got the same error message while using gulp-uglify to compress es6 code.

My code :  
```javascript
const values = Object.values( data );
return new Function( ...( Object.keys( data ) ), 'return (' + n + ')' )( ...values ); 
```

It can be compressed correctly, but if I change `...values` to `...( Object.values( data ) )`, I'll get that error message.

**Comment by BitReign** [comment]
Same here. I'm using it with electron and getting same error for this line:

`const {remote} = require('electron');`

**Comment by terinjokes** [comment]
@NextSeason @BitReign UglifyJS2 doesn't yet support all of ES6, please open an issue with them.
