### ISSUE TITLE
Compress: false, does not work

### ISSUE THREAD

**Issue by jmanuelrosa** [terinjokes/gulp-uglify#70]
Hi,

Gulp-uglify I use to build my webapp. For the development environment, I need to uglify not compress the JS file, so use the compress option: false, and this option does not work. I tried to use all options UglifyJS to false, and neither works.

What happen?

Here's the code:

gulp.task ('compress', function () {
   gulp.src ('app / scripts / *\* / *. js')
     .pipe (uglify ({
          preserveComments: 'some',
          mangle: false,
          compress: false,
          beautify: true
     }))
     .pipe (gulp.dest (dist / scripts'))
});

**Comment by dragonwong** [comment]
I ran into the same issue. I need to **beautify** the code, but not **minify**, and `compress: false` seems not work. :sob:

**Comment by stenmuchow** [comment]
+1

```javascript

            .pipe($.uglify({preserveComments: $.uglifySaveLicense, mangle: false, compress: false})).on('error', options.errorHandler('Uglify'))

```

Same issue here...

**Comment by SpeCT** [comment]
+1

```javascript
var debug = process.env.NODE_ENV !== 'production';

//...

.pipe(uglify({ compress: !debug}))
```

**Comment by xundh** [comment]
meet the same issue

**Comment by ovk** [comment]
gulp-uglify@1.4.1, same issue

**Comment by terinjokes** [comment]
An example that might work is

```javascript
var uglify = require('gulp-uglify');

gulp.task('compress', function() {
  return gulp.src('lib/*.js')
    .pipe(uglify({
      mangle: false,
      compress: false,
      output: { beautify: true }
     }))
    .pipe(gulp.dest('dist'));
});
```

The "compress" outputs change UglifyJS's optimization settings, but UglifyJS would still remove unneeded whitespace. The "output" options controls how UglifyJS outputs the code, including it's formatting.

I'll accept a PR for a recipe example.

**Comment by ovk** [comment]
Thank you, @terinjokes. Adding `output: { beautify: true }` solved the issue.

**Comment by Webcascade** [comment]
Didn't work for me performance wise. I recommend doing this:

`.pipe(function() {
      return gulpif(enabled.jsCompression, uglify());
    })`

check it out here : https://www.npmjs.com/package/gulp-if

**Comment by alexdevero** [comment]
Thank you very much @terinjokes for solution!

**Comment by lordfpx** [comment]
Sorry, but the issue is not fixed since `compress: false` has no effect :-(

**Comment by terinjokes** [comment]
`compress: false` definitely works. The problem is what you want isn't what this setting actually does.

Since you didn't say what you want, I'll leave it as your exercise to read the docs.

**Comment by lordfpx** [comment]
Ok, I get it thanks.
