### ISSUE TITLE
is there a way to invoke in parallel mode to use multiple cpu cores for faster builds?

### ISSUE THREAD

**Issue by tjwebb** [terinjokes/gulp-uglify#72]
I'm wondering if this is possible with gulp-uglify. Or maybe just uglify in general

**Comment by terinjokes** [comment]
For many reasons, including those listed https://github.com/terinjokes/gulp-uglify/pull/79#issuecomment-70745575, I won't be implementing parallel processing at this time.

**Comment by wjordan** [comment]
It is definitely possible to run uglifyjs in parallel mode to use multiple cpu cores for faster builds by using [`child_process.fork`](http://nodejs.org/api/child_process.html#child_process_child_process_fork_modulepath_args_options). This has already been implemented in [webdeps/mnfy](https://github.com/webdeps/mnfy), which depends on [thenables/slave](https://github.com/thenables/slave) to simplify the inter-process communication. I've put together a working prototype uglifyjs gulp plugin using this approach. I can work this implementation into a PR for `gulp-uglify` if there is interest.

**Comment by digitalmaster** [comment]
@wjordan omg yes!! #bump

**Comment by mistakevin** [comment]
@wjordan +1

**Comment by Leikam** [comment]
+1

**Comment by JustFly1984** [comment]
+1, definitely wanted!

**Comment by esvendsen** [comment]
@wjordan +1

**Comment by scythargon** [comment]
@wjordan +1

**Comment by terinjokes** [comment]
This is outside the scope of `gulp-uglify` for the reasons listed in the linked commented above.

This is outside the scope of Gulp for the following reasons: https://github.com/gulpjs/gulp/issues/317#issuecomment-149336502.
