### ISSUE TITLE
Extremely slow

### ISSUE THREAD

**Issue by ilanbiala** [terinjokes/gulp-uglify#73]
Uglifying a file with angular.min.js, angular-material.min.js, and about another 10-15 much smaller files takes almost 5 seconds. This is ridiculously slow.

**Comment by urish** [comment]
See #31

**Comment by ilanbiala** [comment]
@terinjokes any update?

**Comment by schnittstabil** [comment]
Minimizing minimized files looks like a waste of time to me (e.g. d3.**min**.js is already minimized by uglify-js).

Maybe you want to do this only for your deployment? In that case 56 seconds seems tolerable to me.

Anyway, how long takes the minification with the uglify-js CLI? Maybe that's only an issue of [UglifyJS2](https://github.com/mishoo/UglifyJS2/issues) and this issue can be closed?

**Comment by ilanbiala** [comment]
@schnittstabil I'm concatenating and then minifying everything..my files and library files.

**Comment by schnittstabil** [comment]
@ilanbiala I'm aware of that, but consider two gulp task:
* one for your deployment (the one you are using already) and
* a (watch?) task for your red/green/refactor-cycle: concatenating your vendor files, uglifying only your application files

**Comment by joscha** [comment]
maybe we can discuss re-opening #31?

**Comment by kairun** [comment]
+1

**Comment by ilanbiala** [comment]
+1 to reopening #31.

**Comment by tkh44** [comment]
@ilanbiala You can use gulp if to check if a file is already minified in order to skip it.

    var notMinified = function(file) { return !/\.min\.js/.test(file.path); };

    gulp.src(files).pipe(gulp-if(notMinified, uglify())).pipe(etc....);

**Comment by terinjokes** [comment]
I have no control over the minification time within UglifyJS, so there's nothing actionable by me here.

I won't be reopening #31 as it's outside the scope of this module.
