### ISSUE TITLE
Creating EOL characters

### ISSUE THREAD

**Issue by kirkstrobeck** [terinjokes/gulp-uglify#80]
![screen shot 2015-01-21 at 2 09 24 pm](https://cloud.githubusercontent.com/assets/241963/5846251/28aa9ba6-a177-11e4-9e2a-de4c6e90e91a.png)

Using out of the box defaults from gulp uglify.

**Comment by terinjokes** [comment]
@kirkstrobeck do you have the same behavior when using UglifyJS directly? What's the encoding on the input file?

**Comment by kirkstrobeck** [comment]
- Haven’t tried.
- UTF-8

**Comment by Avcajaraville** [comment]
Same here, Im not sure which type of character is getting outputted, but now, Im having break lines on my minified code

**Comment by terinjokes** [comment]
@kirkstrobeck You may be interested in passing `ascii_only: true` as an output option to gulp-uglify.
