### ISSUE TITLE
can not preserve comments rightly

### ISSUE THREAD

**Issue by shijinyu** [terinjokes/gulp-uglify#82]
such as:
```javascript
gulp.task('script',function(){
   gulp.src('js/**/*.js')
     .pipe(uglify({
	   preserveComments:'some'
	 }))
     .pipe(gulp.dest(PATH.js));
})
```
```javascript
/* origin:*/
/*!
  do not delete
*/
var a = String(function(){
	/*!
	<div class="foo">{{bar}}</div>
	*/
    }).replace(/^[^\{]*\{\s*\/\*!?|\*\/[;|\s]*\}$/g, '');

```
output:

```javascript
var a = String(function(){}).replace(/^[^\{]*\{\s*\/\*!?|\*\/[;|\s]*\}$/g, '');
```

Comments with a bang(!) or @preserve, @license, @cc_on,should not be deleted,as README said.

**Comment by terinjokes** [comment]
@shijinyu If you swap the order of the "origin" and "do not delete" comments, does it work?

**Comment by shijinyu** [comment]
No, it doesn't work.
I just want to put the HTML template code in a javascript file,in the form of js comment.But Uglify looks does not correctly identify it.
In addition,if I set the value of preserveComments  as 'all',all comments would be preserved but the comment as this form:
```javascript
String(function(){
    /*! I will be deleted in any case
    <div class="foo">{{bar}}</div>
    */
    })
```

**Comment by taylortom** [comment]
I'm also experiencing the same issue. I can't get any values of `preserveComments` to work besides `none`.

**Comment by shijinyu** [comment]
What a pity! It does be a very strange requirement what I had encountered.

**Comment by terinjokes** [comment]
This might be a regression in how uglifyjs handles preserving comments.
None of the code in this project has changed, and our tests still pass.

I'll look when I return from vacation next week. :sparkles:

**Comment by shijinyu** [comment]
I'm very much obliged to you

**Comment by colinskow** [comment]
I have been having the same issue. I made it work by specifying the comments options manually
```javascript
.pipe(uglify({output: {comments: /^!|@preserve|@license|@cc_on/i}}))
```

**Comment by terinjokes** [comment]
I've just confirmed the proper option is being generated and passed to UglifyJS correctly. Can you reproduce the behavior calling their binary directly?

Also, I note the following from the `--help` screen:

```
Note that currently not *all* comments can be kept when
compression is on, because of dead code removal or
cascading statements into sequences. 
```

**Comment by shijinyu** [comment]
UglifyJS code is too complicated for me, I will try later but I'm not sure if I can reproduce. Thank you so much for making nothing of hardships to find out way and discuss this issue with me.

Go to bed early please. :-)
