### ISSUE TITLE
Output fail message

### ISSUE THREAD

**Issue by NgYueHong** [terinjokes/gulp-uglify#83]
How can I get error message when gulp-uglify fail to compress javascript due to the error in the javascript file?

**Comment by bvaughn** [comment]
If you're willing to edit the source a bit, gulp-uglify's inner Uglify JS package (node_modules/gulp-uglify/node_modules/uglify-js) has a `lib/parser.js` file that  defines a `JS_Parse_Error` method. When the error is instantiated, just pass the message to like so:

```js
this.stack = new Error(this.toString()).stack;
```

This will change the errors you see from this:

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error
    at new JS_Parse_Error (/Users/bvaughn/Documents/git/task-runner/node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:189:18)
...
```

To something more useful like this:

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Unexpected token: punc (:) (line: 1, col: 10, pos: 10)

undefined
    at new JS_Parse_Error (/Users/bvaughn/Documents/git/task-runner/node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:189:18)
...
```

I realize this is not a great solution, but it may help unblock you. :)

**Comment by jacqueslareau** [comment]
Probably related to #85

**Comment by terinjokes** [comment]
@NgYueHong Please see this section in the gulp documentation: https://github.com/gulpjs/gulp/blob/master/docs/recipes/combining-streams-to-handle-errors.md#combining-streams-to-handle-errors
