### ISSUE TITLE
Tricky case where Uglify drops a parameter whereas it should not be considered as unused

### ISSUE THREAD

**Issue by imbibinebe** [terinjokes/gulp-uglify#87]
Hi there,

Here are to class functions illustrating that a bad coding habit can break compressed code while it's was working when not compressed...

Those functions are event handlers which need to access the event passed as a parameter. Let's call this event 'e' because we are too lazy to be careful enough ...
Inside those functions we also need a try catch block in a closure (like in a forEach loop for example) for some reason. Again, we are to lazy to be careful and we call this exception 'e', like the event ...
Obviously, doing this could be considered as a bad practice. It's obvious, looking at those small functions, that we should fear something like a conflict :dancers:
However, a function can be big and complex enough so that we didn't notice the problem. At least when it works with uncompressed code.

```javascript
    //~ this works when not compressed
	testUglifyKO: function(e) {
        (function(){
			try{console.log(e);}catch(e){}
		})();
	},
    //~ but the following compressed code doesn't work since e parameter is dropped
    //~ testUglifyKO:function(){!function(){try{console.log(t)}catch(t){}}()}

    //~ this works when not compressed
	testUglifyOK: function(e) {
        (function(){
			try{console.log(e);}catch(excp){}
		})();
	},
    //~ the following compressed code works as well
    //~ testUglifyOK:function(t){!function(){try{console.log(t)}catch(e){}}()}
```

As soon as compressed code should work like uncompressed one I consider this is a uglify bug. But I might be wrong :)

PS: i use uglify with no compression options (default options)

Best

**Comment by terinjokes** [comment]
@imbibinebe I agree, it definitely looks like an UglifyJS bug. Have you tried using UglifyJS directly? Do you get the same error?

If you do, please file an issue with the UglifyJS project: https://github.com/mishoo/UglifyJS2

**Comment by imbibinebe** [comment]
I didn't try using UglifyJS directly and i unfortunately have no time for this. I think it's not too difficult to test it, then i'll let one of UglifyJS contributor test it for me :D
One thing I am sure is that fixing this bug might solve many problems. It did on my side at least :)

**Comment by imbibinebe** [comment]
https://github.com/mishoo/UglifyJS2/issues/650#issuecomment-78168065
Is it possible to use this --screw-ie8 option with gulp-uglify ?
