### ISSUE TITLE
Add "quote_style" option

### ISSUE THREAD

**Issue by aendrew** [terinjokes/gulp-uglify#88]
UglifyJS2 v2.4.17 has a new option, "quote_style," which allows the preservation of quote marks. This is extremely helpful when writing a script that outputs JSON in a particular way.

I just did a [PR](https://github.com/gruntjs/grunt-contrib-uglify/pull/306) for grunt-contrib-uglify, will port that to this later this afternoon.

**Comment by terinjokes** [comment]
Just curious why this needs to be a gulp-uglify option. You can pass compress, mangle and output options that are pass forward to UglifyJS.

(Obviously, the upgrade is still required)

**Comment by aendrew** [comment]
@terinjokes No particular reason, other than the syntax (`0` for original behaviour; `3` to preserve original quotes) is a bit unintuitive. It's probably not as necessary as the `preserveComments` helper option, though.

**Comment by terinjokes** [comment]
Have you suggested getting these options as aliases in UglifyJS first?

**Comment by aendrew** [comment]
@terinjokes That... Is a much better approach. I'll close this request and do that instead. Thanks!

**Comment by jshado1** [comment]
I'm not seeing a post from @aendrew in [mishoo/UglifyJS2](https://github.com/mishoo/UglifyJS2). Laking this functionality is very frustrating.

**Comment by terinjokes** [comment]
@jshado1 That should be supported as of the next version of gulp-uglify

**Comment by aendrew** [comment]
@terinjokes IIRC, didn't quote_style already work, and my PR was simply to add some aliases?

**Comment by SuperAL** [comment]
You can prevents stripping quotes from property names in object literals by setting `keep_quoted_props` to `true`:
```js
.pipe(uglify({
    output: {
      keep_quoted_props: true // when turned on, prevents stripping quotes from property names in object literals. 
    }
  }))
```
