### ISSUE TITLE
Feature: verbose options

### ISSUE THREAD

**Issue by sheo13666** [terinjokes/gulp-uglify#91]
Add verbose options for files that minify

**Comment by sindresorhus** [comment]
What should verbose mode do? If you just want the files listed you should rather use [`gulp-debug`](https://github.com/sindresorhus/gulp-debug).

**Comment by sheo13666** [comment]
@sindresorhus thanks

**Comment by sheo13666** [comment]
@sindresorhus how i can get size of files after uglify, gulp-debug title is string, not as async function

**Comment by sindresorhus** [comment]
@sheo13666 https://github.com/sindresorhus/gulp-size
