### ISSUE TITLE
Unexpected token error when using gulp-uglify with js code generated from babel.js

### ISSUE THREAD

**Issue by cnbuff410** [terinjokes/gulp-uglify#95]
I'm sure it's because of the ECMA6 code because it won't happen otherwise.

Here is the example ecma6 code:

  class calc {
    constructor(){
      console.log('Calc constructor');
    }
    add(a, b){
      return a + b;
    }
  }

  var c = new calc();
  console.log(c.add(4,5));

I put babel and uglify into gulp task. Babel is running first, then uglify. Something like this:

  runSequence('babel', 'styles', 'html', cb);

in 'html' I run uglify like this

return gulp.src('app/**/*.html')
       // Concatenate And Minify JavaScript
       .pipe($.if('*.js', $.uglify({preserveComments: 'some'}).on('error', gutil.log)))

However, when I run the gulp, it always gives me this error:

[20:04:17] { [Error: /Users/cnbuff410/Work/web/app/scripts/forum.min.js: Unexpected token: name (calc)]
  message: '/Users/cnbuff410/Work/web/app/scripts/forum.min.js: Unexpected token: name (calc)',
  fileName: '/Users/cnbuff410/Work/web/app/scripts/forum.min.js',
  lineNumber: 61,
  stack: 'Error\n    at new JS_Parse_Error (/Users/cnbuff410/Work/we/node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:189:18)\n    at js_error (/Users/cnbuff410/Work/web/node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:197:11)\n    at croak (/Users/cnbuff410/Work/web/node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:661:41)\n    at token_error (/Users/cnbuff410/Work/web/node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:665:9)\n    at unexpected (/Users/cnbuff410/Work/web/node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:671:9)\n    at semicolon (/Users/cnbuff410/Work/web/node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:691:43)\n    at simple_statement (/Users/cnbuff410/Work/web/node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:865:73)\n    at /Users/cnbuff410/Work/web/node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:738:19\n    at /Users/cnbuff410/Work/web/node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:704:24\n    at block_ (/Users/cnbuff410/Work/web/node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:978:20)',
  showStack: false,
  showProperties: true,
  plugin: 'gulp-uglify' }

events.js:85
      throw er; // Unhandled 'error' event

**Comment by muzuiget** [comment]
Maybe similar #97, try to update latest uglifyjs.

**Comment by cnbuff410** [comment]
I am using latest version I believe

> npm list | grep uglify

├─┬ gulp-uglify@1.1.0
│ ├─┬ uglify-js@2.4.16
│ │ └── uglify-to-browserify@1.0.2
│ │ │     │     └── uglify-js@1.1.1

**Comment by cnbuff410** [comment]
oops, not a good format, but basically that's the output of npm list

**Comment by terinjokes** [comment]
Published 1.2.0 which includes a newer UglifyJS that should resolve issues with Babel.
